export const ALL_EXERCISES = [
  // A
  "Ab Wheel Rollout",
  "Abcoaster",
  "Air Bike",
  "Archer Pull Ups",
  "Archer Push Ups",
  "Arnold Press",
  "Assisted Chin Ups",
  "Assisted Dips",
  "Assisted Muscle Ups",
  "Assisted Pull Ups",

  // B
  "Back Extension",
  "Back Lever",
  "Balance Board Squat",
  "Band Assisted Pull Ups",
  "Barbell Calf Raise",
  "Barbell Clean",
  "Barbell Concentration Curl",
  "Barbell Curl",
  "Barbell Flexion Row",
  "Barbell Front Raise",
  "Barbell Glute Bridge",
  "Barbell Hack Squat",
  "Barbell Lunge",
  "Barbell Overhead Press",
  "Barbell Power Shrug",
  "Barbell Pullover",
  "Barbell Reverse Curl",
  "Barbell Reverse Lunge",
  "Barbell Row",
  "Barbell Shrug",
  "Barbell Step Up",
  "Barbell Thruster",
  "Barbell Upright Row",
  "Barbell Z Press",
  "Bayesian Curl",
  "Behind the Back Deadlift",
  "Behind the Back Neck Press",
  "Behind the Back Barbell Shrug",
  "Behind the Neck Press",
  "Bench Dips",
  "Bench Pin Press",
  "Bench Press",
  "Bench Pull",
  "Bent Arm Barbell Pullover",
  "Bent Over Dumbbell Row",
  "Bent Over Row",
  "Bicycle Crunch",
  "Bicep Curl",
  "Bird Dog",
  "Bodyweight Squat",
  "Bodyweight Calf Raise",
  "Bodyweight Concentration Curl",
  "Bodyweight Good Morning",
  "Bodyweight Kneeling Tricep Extension",
  "Bodyweight Lateral Raise",
  "Bodyweight Military Press",
  "Bodyweight Overhead Tricep Extension",
  "Bodyweight Tricep Extension",
  "Box Jump",
  "Box Squat",
  "Broad Jump",
  "Bulgarian Split Squat",
  "Burpees",

  // C
  "Cable Bent Over Row",
  "Cable Bicep Curl",
  "Cable Chest Fly",
  "Cable Chest Press",
  "Cable Crossover",
  "Cable Crunch",
  "Cable External Rotation",
  "Cable Face Pull",
  "Cable Front Raise",
  "Cable Hammer Curl",
  "Cable Internal Rotation",
  "Cable Kickback",
  "Cable Lateral Raise",
  "Cable Leg Curl",
  "Cable Leg Extension",
  "Cable Overhead Tricep Extension",
  "Cable Pull Through",
  "Cable Rear Delt Fly",
  "Cable Reverse Curl",
  "Cable Reverse Fly",
  "Cable Reverse Wrist Curl",
  "Cable Rope Overhead Extension",
  "Cable Rope Pushdown",
  "Cable Shrug",
  "Cable Tricep Kickback",
  "Cable Upright Row",
  "Cable Woodchopper",
  "Cable Wrist Curl",
  "Cable Y Raise",
  "Calf Raises",
  "Captain's Chair Knee Raise",
  "Captain's Chair Leg Raise",
  "Cheat Curl",
  "Chest Dip",
  "Chest Press",
  "Chest Press Machine",
  "Chest Supported Dumbbell Row",
  "Chest Supported Dumbbell Shrug",
  "Chest Supported T Bar Row",
  "Chin Ups",
  "Clamshells",
  "Clap Pull Ups",
  "Clap Push Ups",
  "Clean",
  "Clean and Jerk",
  "Clean and Press",
  "Clean High Pull",
  "Clean Pull",
  "Close Grip Bench Press",
  "Close Grip Dumbbell Bench Press",
  "Close Grip Incline Bench Press",
  "Close Grip Lat Pulldown",
  "Close Grip Pull Ups",
  "Close Grip Push Up",
  "Crossover Lunge",
  "Cross Body Cable Tricep Extension",
  "Cross Body Hammer Curl",
  "Cross Body Lat Pull Around",
  "Crunch",
  "Crunch Machine",
  "Cycling",

  // D
  "Dead Bug",
  "Dead Hang",
  "Deadlift",
  "Decline Bench Press",
  "Decline Crunch",
  "Decline Dumbbell Press",
  "Deficit Deadlift",
  "Decline Dumbbell Fly",
  "Decline Push Ups",
  "Decline Pike Push Ups",
  "Decline Sit-Up",
  "Deficit Push Ups",
  "Diamond Push Ups",
  "Double Crunch",
  "Dragon Flag",
  "Dumbbell Bench Pull",
  "Dumbbell Calf Raise",
  "Dumbbell Clean and Press",
  "Dumbbell External Rotation",
  "Dumbbell Face Pull",
  "Dumbbell Floor Press",
  "Dumbbell Front Squat",
  "Dumbbell Hang Clean",
  "Dumbbell High Pull",
  "Dumbbell Incline Y Raise",
  "Dumbbell Larsen Press",
  "Dumbbell Push Press",
  "Dumbbell Reverse Curl",
  "Dumbbell Reverse Fly",
  "Dumbbell Reverse Wrist Curl",
  "Dumbbell Side Bend",
  "Dumbbell Snatch",
  "Dumbbell Spider Curl",
  "Dumbbell Squat",
  "Dumbbell Tricep Kickback",
  "Dumbbell Upright Row",
  "Dumbbell Walking Calf Raise",
  "Dumbbell Wrist Curl",
  "Dumbbell Bench Press",
  "Dumbbell Bulgarian Split Squat",
  "Dumbbell Clean",
  "Dumbbell Concentration Curl",
  "Dumbbell Bicep Curl",
  "Dumbbell Deadlift",
  "Dumbbell Flyes",
  "Dumbbell Front Raise",
  "Dumbbell Hammer Curl",
  "Incline Dumbbell Bench Press",
  "Dumbbell Lateral Raise",
  "Dumbbell Lunge",
  "Dumbbell Overhead Press",
  "Dumbbell Pullover",
  "Dumbbell Romanian Deadlift",
  "Dumbbell Row",
  "Dumbbell Shoulder Press",
  "Dumbbell Shrug",
  "Dumbbell Skullcrusher",
  "Dumbbell Split Squat",
  "Dumbbell Step Up",
  "Dumbbell Thruster",
  "Dumbbell Triceps Extension",
  "Dumbbell Z Press",
  "Depth Jump",
  "Dip Machine",
  "Dips",
  "Donkey Calf Raise",
  "Double Under",
  "Drag Curl",

  // E
  "Elbow to Knee Crunch",
  "Elliptical Trainer",
  "Elevated Push Up",
  "Explosive Push Up",
  "Explosive Squat Jump",
  "EZ Bar Lying Triceps Extension",
  "EZ Bar Preacher Curl",
  "EZ Bar Spider Curl",
  "EZ Bar Curl",
  "EZ Bar Skullcrusher",
  "EZ Bar Upright Row",
  "External Shoulder Rotation",

  // F
  "Face Pull",
  "Feet Elevated Push Up",
  "Fingertip Push Up",
  "Fire Hydrant",
  "Floor Press",
  "Farmer's Walk",
  "Floor Hip Abduction",
  "Floor Hip Extension",
  "Floor T Raise",
  "Flutter Kick",
  "Forward Lunge",
  "Front Lever",
  "Front Raise",
  "Front Squat",

  // G
  "GHD Back Extension",
  "GHD Sit Up",
  "Glute Bridge",
  "Glute Ham Raise",
  "Glute Kickback",
  "Goblet Squat",
  "Good Morning",
  "Groin Stretch Lunge",

  // H
  "Hack Squat",
  "Hammer Curl",
  "Hammer Strength Chest Press",
  "Hammer Strength Row",
  "Hand Release Push Up",
  "Handstand",
  "Hack Squat Calf Raise",
  "Half Kneeling One Arm Lat Pulldown",
  "Half Squat",
  "Hand Grippers",
  "Hanging Windshield Wipers",
  "Heel Touch",
  "Heel-Elevated Squat",
  "Hex Bar Deadlift",
  "Hex Bar Shrug",
  "High Plank",
  "High Pulley Crunch",
  "High to Low Cable Fly",
  "Hip Extension",
  "Hip Thrust",
  "Handstand Push Up",
  "Hang Clean",
  "Hang Power Clean",
  "Hang Snatch",
  "Hanging Knee Raise",
  "Hanging Leg Raise",
  "High Pull Up",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Horizontal Leg Press",

  // I
  "Incline Bench Press",
  "Incline Dumbbell Curl",
  "Incline Push Up",
  "Incline Cable Curl",
  "Incline Dumbbell Fly",
  "Incline Hammer Curl",
  "Incline Machine Press",
  "Incline Side Lying Lateral Raise",
  "Inverted Row",
  "Iron Cross",

  // J
  "Jackknife Sit Up",
  "Jammer Press",
  "Jefferson Curl",
  "Jefferson Deadlift",
  "Jefferson Squat",
  "Jerk",
  "Jump Rope",
  "Jump Shrug",
  "Jump Squat",
  "Jumping Jacks",

  // K
  "Kettlebell Clean",
  "Kettlebell Deadlift",
  "Kettlebell Goblet Squat",
  "Kettlebell Snatch",
  "Kettlebell Swing",
  "Kettlebell Thruster",
  "Kettlebell Turkish Get Up",
  "Kipping Handstand Push Up",
  "Kipping Pull Up",
  "Knee Cobra Push Ups",
  "Knee Pike Push Ups",
  "Knee Push Ups",
  "Knee Raise",
  "Knees to Elbows",
  "Kneeling Finger Press",
  "Kneeling Fist to Palm",
  "Knuckle Push Ups",
  
  // L
  "L Pull Up",
  "Landmine Press",
  "Landmine Row",
  "Lat Pulldown",
  "Lateral Box Jump",
  "Lateral Lunge",
  "Lawnmower Row",
  "Leg Curl",
  "Leg Extension",
  "Leg Press",
  "Leg Press Calf Raise",
  "Lying Leg Raises",
  "Lunges",
  "L Sit",
  "Landmine Squat",
  "Larsen Press",
  "Low Plank",
  "Low to High Cable Fly",
  "Lying Cable Curl",
  "Lying Dumbbell Tricep Extension",
  "Lying Leg Curl",
  "Lying Tricep Extension",

  // M
  "Machine Bicep Curl",
  "Machine Chest Press",
  "Machine Fly",
  "Machine Back Extension",
  "Machine Calf Press",
  "Machine Calf Raise",
  "Machine Chest Fly",
  "Machine Glute Kickback",
  "Machine High Row",
  "Machine Hip Thrust",
  "Machine Lateral Raise",
  "Machine Shoulder Press",
  "Machine Shrug",
  "Machine Tricep Extension",
  "Machine Pullover",
  "Machine Reverse Fly",
  "Machine Row",
  "Machine Seated Crunch",
  "Meadows Row",
  "Military Press",
  "Muscle Snatch",
  "Medicine Ball Slam",
  "Mountain Climbers",
  "Muscle Up",

  // N
  "Narrow Grip Bench Press",
  "Narrow Grip Push Up",
  "Neck Curl",
  "Neck Extension",
  "Neck Flexion",
  "Neck Lateral Flexion",
  "Neck Rotation",
  "Negative Chin Up",
  "Negative Pull Up",
  "Neutral Grip Lat Pulldown",
  "Neutral Grip Chin Up",
  "Neutral Grip Pull Up",
  "Nordic Curl",
  "No Equipment Air Bike",

  // O
  "One Arm Band Row",
  "One Arm Barbell Row",
  "One Arm Cable Curl",
  "One Arm Cable Extension",
  "One Arm Cable Fly",
  "One Arm Seated Cable Row",
  "One Arm Chest Press",
  "One Arm Clean",
  "One Arm Deadlift",
  "One Arm Dumbbell Bench Press",
  "One Arm Dumbbell Curl",
  "One Arm Dumbbell Fly",
  "One Arm Dumbbell Lateral Raise",
  "One Arm Dumbbell Overhead Press",
  "One Arm Dumbbell Pullover",
  "One Arm Dumbbell Row",
  "One Arm Dumbbell Shrug",
  "One Arm Dumbbell Triceps Extension",
  "One Arm Floor Press",
  "One Arm Cable Front Raise",
  "One Arm Dumbbell Preacher Curl",
  "One Arm Landmine Press",
  "One Arm Lat Pulldown",
  "One Arm Machine Reverse Fly",
  "One Arm Pull Up",
  "One Arm Kettlebell Clean",
  "One Arm Kettlebell Deadlift",
  "One Arm Kettlebell Row",
  "One Arm Push Up",
  "One Arm Row (Machine)",
  "One Arm Smith Machine Row",
  "One Arm Turkish Get Up",
  "Open Chain Cable Row",
  "Overhead Cable Curl",
  "Overhead Dumbbell Press",
  "Overhead Lunge",
  "Overhead Medicine Ball Slam",
  "Overhead Plate Carry",
  "Overhead Rope Extension",
  "Overhead Squat",
  "Overhead Tricep Extension",
  "Overhead Walk",
  "Overhead Y Raise",

  // P
  "Pallof Press",
  "Pause Deadlift",
  "Pause Squat",
  "Paused Bench Press",
  "Paused Incline Bench Press",
  "Pendulum Squat",
  "Pilates",
  "Pin Squat",
  "Pistol Squat",
  "Planche",
  "Pec Deck Fly",
  "Pendlay Row",
  "Physio Ball Crunch",
  "Pike Push Up",
  "Piriformis Stretch",
  "Plank",
  "Plank to Push Up",
  "Plate Curl",
  "Plate Front Raise",
  "Plate Pinch Hold",
  "Power Clean",
  "Power Snatch",
  "Preacher Curl",
  "Prone Y Raise",
  "Pull Over",
  "Pull-Ups",
  "Push Jerk",
  "Push Press",
  "Push-Up",
  "Planche Push Up",
  "Plank Lean",
  "Preacher Hammer Curl",
  "Press Around",
  "Pseudo Planche Push Up",

  // Q
  "Quad Extension",
  "Quadruped Shoulder Tap",

  // R
  "Rack Pull",
  "Rear Delt Fly",
  "Renegade Row",
  "Reverse Crunch",
  "Reverse Curl",
  "Reverse Fly",
  "Reverse Hyperextension",
  "Reverse Lunge",
  "Ring Dip",
  "Ring Muscle Up",
  "Ring Push Up",
  "Rope Climb",
  "Rope Face Pull",
  "Rope Hammer Curl",
  "Rope Pushdown",
  "Rowing Machine",
  "Russian Twist",
  "Reverse EZ Bar Curl",
  "Reverse Grip Bench Press",
  "Reverse Grip Bent Over Row",
  "Reverse Grip Lat Pulldown",
  "Reverse Grip Push Up",
  "Reverse Grip Tricep Pushdown",
  "Reverse Nordic Curl",
  "Reverse Plank",
  "Reverse Wrist Curl",
  "Roman Chair Side Bend",
  "Romanian Deadlift",

  // S
  "Scissor Kick",
  "Seated Calf Raise",
  "Seated Cable Row",
  "Seated Leg Curl",
  "Seated Overhead Press",
  "Seated Row",
  "Shoulder Press",
  "Side Lateral Raise",
  "Side Plank",
  "Single Arm Cable Row",
  "Single Arm Dumbbell Press",
  "Single Arm Row",
  "Single Leg Deadlift",
  "Single Leg Glute Bridge",
  "Single Leg Press",
  "Sit Up",
  "Skater Squat",
  "Skullcrusher",
  "Sled Push",
  "Side Crunch",
  "Side Leg Raise",
  "Side Lunge",
  "Side Lying Hip Adduction",
  "Single Arm Hammer Curl",
  "Single Arm Tricep Pushdown",
  "Single Leg Dumbbell Deadlift",
  "Single Leg Extension",
  "Single Leg Lying Leg Curl",
  "Single Leg Romanian Deadlift",
  "Single Leg Seated Calf Raise",
  "Single Leg Squat",
  "Sissy Squat",
  "Smith Machine Bench Press",
  "Smith Machine Bent Over Row",
  "Smith Machine Bulgarian Split Squat",
  "Smith Machine Calf Raise",
  "Smith Machine Incline Bench Press",
  "Smith Machine Reverse Grip Bent Over Row",
  "Smith Machine Shoulder Press",
  "Smith Machine Shrug",
  "Smith Machine Sissy Squat",
  "Smith Machine Squat",
  "Snatch Pull",
  "Snatch",
  "Snatch Grip Deadlift",
  "Snow Angel",
  "Split Squat",
  "Split Squat Jump",
  "Spider Curl",
  "Split Jerk",
  "Spoto Press",
  "Standing Cable Crunch",
  "Standing Machine Lateral Raise",
  "Squat",
  "Squat Jump",
  "Stair Climber",
  "Standing Calf Raise",
  "Standing Cable Row",
  "Standing Leg Curl",
  "Standing Leg Raise",
  "Step Up",
  "Step Up with Knee Raise",
  "Stiff Leg Deadlift",
  "Straight Arm Pulldown",
  "Strict Curl",
  "Strict Press",
  "Sumo Deadlift",
  "Sumo Squat",
  "Superman",
  "Safety Bar Squat",
  "Seated Dip Machine",
  "Seated Dumbbell Curl",
  "Seated Dumbbell Shoulder Press",
  "Seated Dumbbell Tricep Extension",
  "Seated Hammer Curl",
  "Seated Shoulder Press",
  "Seated Smith Machine Shoulder Press",
  "Shoulder Pin Press",

  // T
  "Table Inverted Row",
  "Tate Press",
  "Tiger Bend Push Ups",
  "Toes to Bar",
  "Torso Rotation Machine",
  "Tricep Extension (Barbell)",
  "T Bar Row",
  "Towel Pull Up",
  "Tricep Dips",
  "Triceps Extension",
  "Triceps Kickback",
  "Tricep Pushdown",
  "Trap Bar Deadlift",
  "Tree Pose",
  "Turkish Get Up",

  // U
  "Upright Row",
  "Upright Shoulder Raise",
  "Uttanasana (Forward Bend)",

  // V
  "V Squat",
  "V Ups",
  "Vertical Leg Press",
  "Vertical Traction Machine",
  "Viking Press",
  "V Sit",
  "Vertical Jump",
  "Volleyball Serve",

  // W
  "Wall Ball Shot",
  "Wall Sit",
  "Walking Lunge",
  "Water Rowing",
  "Weighted Pull Up",
  "Wide Grip Lat Pulldown",
  "Waiter Curl",
  "Wall Push Up",
  "Wide Grip Bench Press",
  "Wide Grip Chest Press",
  "Wide Grip Push Up",
  "Wide Grip Seated Cable Row",
  "Wide Grip Pull Up",
  "Windmill",
  "Wrist Curl",

  // X
  "X Band Walk",

  // Y
  "Y Raise",
  "Yoke Walk",
  "Yates Row",

  // Z
  "Z Press",
  "Zercher Deadlift",
  "Zottman Curl",
  "Zercher Squat",
];