// constants/exercises/approvedExercises.js

// Everything from rotationGroups.js (deduped) + a core “junk” bucket (also deduped).
export const APPROVED_EXERCISES = [
  // --- Rotation groups (from rotationGroups.js) ---
  "Deadlift",
  "Romanian Deadlift",
  "Trap Bar Deadlift",
  "Pause Deadlift",
  "Rack Pull",
  "Behind the Back Deadlift",
  "Hex Bar Deadlift",

  "Squat",
  "Leg Press",
  "Horizontal Leg Press",
  "Single Leg Press",
  "Vertical Leg Press",
  "Front Squat",
  "Goblet Squat",
  "Hack Squat",
  "Barbell Hack Squat",
  "Box Squat",
  "Bulgarian Split Squat",
  "Dumbbell Bulgarian Split Squat",
  "Dumbbell Split Squat",
  "Kettlebell Goblet Squat",
  "Pause Squat",
  "Smith Machine Bulgarian Split Squat",
  "Smith Machine Squat",
  "Split Squat",

  "Bench Press",
  "Dumbbell Bench Press",
  "Machine Chest Press",
  "Smith Machine Bench Press",
  "Dumbbell Flyes",
  "Cable Chest Press",
  "Cable Crossover",
  "Dips",
  "Chest Dip",
  "Chest Press",

  "Incline Bench Press",
  "Incline Dumbbell Bench Press",
  "Incline Dumbbell Fly",
  "Smith Machine Incline Bench Press",

  "Barbell Overhead Press",
  "Seated Dumbbell Shoulder Press",
  "Machine Shoulder Press",
  "Dumbbell Shoulder Press",
  "Smith Machine Shoulder Press",
  "Seated Smith Machine Shoulder Press",
  "Dumbbell Overhead Press",
  "One Arm Dumbbell Overhead Press",
  "Overhead Dumbbell Press",
  "Seated Overhead Press",

  "Barbell Shrug",
  "Behind the Back Barbell Shrug",
  "Hex Bar Shrug",

  "Barbell Row",
  "Seated Cable Row",
  "Bent Over Dumbbell Row",
  "Bent Over Row",
  "Chest Supported Dumbbell Row",
  "Dumbbell Row",
  "One Arm Seated Cable Row",
  "One Arm Dumbbell Row",
  "One Arm Kettlebell Row",
  "Pendlay Row",
  "Smith Machine Bent Over Row",
  "T Bar Row",
  "Machine Row",
  "Cable Face Pull",

  "Pull-Ups",
  "Lat Pulldown",
  "Neutral Grip Pull Up",
  "Chin Ups",
  "One Arm Lat Pulldown",
  "Reverse Grip Lat Pulldown",
  "Straight Arm Pulldown",

  "Barbell Curl",
  "EZ Bar Curl",
  "Bayesian Curl",
  "Bicep Curl",
  "Cable Bicep Curl",
  "Dumbbell Bicep Curl",
  "Dumbbell Hammer Curl",
  "EZ Bar Preacher Curl",
  "Hammer Curl",
  "Incline Dumbbell Curl",
  "Incline Hammer Curl",
  "One Arm Cable Curl",
  "One Arm Dumbbell Preacher Curl",
  "Overhead Cable Curl",
  "Preacher Curl",
  "Seated Dumbbell Curl",
  "Seated Hammer Curl",
  "Barbell Concentration Curl",
  "Barbell Reverse Curl",
  "Dumbbell Reverse Curl",

  "Tricep Pushdown",
  "Overhead Tricep Extension",
  "Skullcrushers",
  "Tricep Dips",
  "Cable Overhead Tricep Extension",
  "Cable Rope Overhead Extension",
  "Arnold Press",
  "Bench Dips",
  "Cross Body Cable Tricep Extension",
  "Dumbbell Skull Crusher",
  "Dumbbell Tricep Extension",
  "EZ Bar Skullcrusher",
  "Lying Tricep Extension",
  "One Arm Cable Extension",
  "One Arm Dumbbell Triceps Extension",
  "Single Arm Tricep Pushdown",
  "Tate Press",
  "Tricep Extension",
  "Tricep Rope Push Down",

  "Barbell Calf Raise",
  "Dumbbell Calf Raise",
  "Hack Squat Calf Raise",
  "Leg Press Calf Raise",
  "Seated Calf Raise",
  "Smith Machine Calf Raise",

  // --- Core “junk” bucket (keep this tight & common) ---
  "Plank",
  "Side Plank",
  "Russian Twist",
  "Dead Bug",
  "Bird Dog",
  "Crunch",
  "Cable Crunch",
  "Reverse Crunch",
  "Pallof Press",
  "Cable Woodchopper",
  "Hanging Knee Raise",
  "Hanging Leg Raise",
  "Captain's Chair Knee Raise",
  "Captain's Chair Leg Raise",
  "Ab Wheel Rollout",
  "Decline Sit-Up",
  "Sit Up",
  "V Ups",
  "Toes to Bar",
  "Lying Leg Raises",
];