export const DESCRIPTIONS = {

  // A
  "Ab Wheel Rollout": "Kneel, grip the ab wheel handles, brace your core. Roll the wheel forward slowly until your torso is nearly parallel to the floor, then pull it back in using your abs and hips, keeping arms straight.",
  "Abcoaster": "Kneel on the AbCoaster, hands on the pads. Pull your knees up toward your chest, contracting your abs. Lower your legs back under control, resisting gravity with your core.",
  "Air Bike": "Sit on the dual-action bike. Pedal while pushing and pulling the handles simultaneously. Keep a steady pace, pushing through legs and pulling with arms for the full time.",
  "Archer Pull Ups": "Hang from a pull-up bar with a wide grip. Pull up and shift your body to one side, extending the opposite arm straight. Alternate sides.",
  "Archer Push Ups": "Perform push-ups with one arm bent and the other extended out to the side. Lower chest toward the bent arm, then push back up and switch sides.",
  "Arnold Press": "Hold dumbbells at shoulders with palms facing you. Press upward while rotating wrists so palms face forward at the top. Reverse the motion back down.",
  "Assisted Chin Ups": "Use a band or machine to reduce bodyweight. Grip underhand and pull your chin above the bar, then lower with control.",
  "Assisted Dips": "Use a dip machine or resistance band to lessen weight. Lower your body until elbows are ~90°, then push back up until arms are straight.",
  "Assisted Muscle Ups": "With band/machine assistance, pull your chest to bar, then transition your chest over it and press down into a dip position before lowering.",
  "Assisted Pull Ups": "Use assistance to do pull-ups: grip overhand, pull chin to bar, and lower slowly, with help from band or machine.",

  // B
  "Back Extension": "Lie face down on a back extension bench. Bend at the waist and lower your upper body, then raise until your body is straight. Squeeze glutes at the top.",
  "Back Lever": "Hang from a bar or rings, then rotate your body forward so you're horizontal and face-down, with arms straight and torso in line. Hold.",
  "Balance Board Squat": "Stand on a balance board with feet shoulder-width. Perform squats while keeping steady and board balanced underfoot.",
  "Band Assisted Pull Ups": "Loop a band over the pull-up bar and place a knee or foot in it. Perform pull-ups with band support until chin clears bar.",
  "Barbell Calf Raise": "Stand holding a barbell across your shoulders. Raise your heels off the ground as high as possible, then lower back down slowly.",
  "Barbell Clean": "Stand with barbell on floor. Bend and grip it, explosively pull it upward, shrug and flip elbows under at shoulder height. Catch in front-rack position.",
  "Barbell Concentration Curl": "Sit on a bench, lean forward, elbow on inner thigh, curl barbell upward with strict form, then lower under control.",
  "Barbell Curl": "Stand tall, grip barbell palms-up shoulder-width. Curl upward to shoulders, keeping elbows close, then lower slowly.",
  "Barbell Flexion Row": "Bent-over row variation using a curling motion to emphasize biceps involvement.",
  "Barbell Front Raise": "Stand holding barbell with palms down. Lift the bar to shoulder height with straight arms, then lower under control.",
  "Barbell Glute Bridge": "Lie on your back with barbell on hips. Bend knees, plant feet. Lift hips until body forms line from shoulders to knees, squeeze glutes.",
  "Barbell Hack Squat": "Stand with a barbell held behind you at mid-calf. Squat down by bending knees/hips, then push back up keeping chest upright.",
  "Barbell Lunge": "With barbell on shoulders, step forward into lunge until front thigh is parallel. Push through front heel to return and repeat on the other leg.",
  "Barbell Overhead Press": "Stand or sit, hold barbell at shoulders. Press overhead until arms lock out, then lower to shoulders with control.",
  "Barbell Power Shrug": "Hold barbell, shrug shoulders upward explosively, keeping arms straight. Lower under control.",
  "Barbell Pullover": "Lie on bench cross-body with barbell. Hold it over chest, lower behind head with straight arms, then pull back over chest.",
  "Barbell Reverse Curl": "Hold barbell palms down. Curl upward keeping elbows still, squeeze forearms, and lower back down slowly.",
  "Barbell Reverse Lunge": "Stand with barbell. Step backward into lunge until front thigh is parallel. Push through front heel to return.",
  "Barbell Row": "Bend over with barbell, back flat. Pull barbell to abdomen, squeeze shoulder blades, then lower with control.",
  "Barbell Shrug": "Stand holding barbell arms straight. Shrug shoulders up toward ears, pause, then lower back down.",
  "Barbell Step Up": "Holding barbell, step onto box or bench with one foot, drive through heel to stand, step down and switch legs.",
  "Barbell Thruster": "From front-rack squat position, squat down then drive up and transition into overhead press in one fluid motion.",
  "Barbell Upright Row": "Hold barbell palms down. Pull it straight up to chest level, elbows flared, then lower slowly.",
  "Barbell Z Press": "Sit on floor legs straight, hold barbell at shoulders. Press overhead keeping spine stable, then lower to shoulders.",
  "Bayesian Curl": "Stand and curl barbell while leaning slightly back, letting elbows move behind to emphasize the bicep peak.",
  "Behind the Back Deadlift": "Stand with barbell behind legs. Bend hips/knees, grab bar and drive hips forward to lift, keeping your back straight.",
  "Behind the Back Neck Press": "Place barbell behind your neck at shoulders. Press upward until arms lock, then lower slowly.",
  "Behind the Back Barbell Shrug": "Shrug the barbell behind your back to isolate the upper traps.",
  "Behind the Neck Press": "Overhead press starting behind the head, targeting shoulders with emphasis on rear delts.",
  "Bench Dips": "Place hands on bench behind you, extend legs forward. Lower your body by bending elbows until ~90°, then press up.",
  "Bench Pin Press": "Set pins on bench press rack to limit bar range. Lower bar to pins, press up from that position.",
  "Bench Press": "Lie flat on bench with barbell at chest. Grip shoulder-width, lower bar to chest, then press upward until arms lock.",
  "Bench Pull": "Lie chest-down on bench, grab dumbbells or bar below. Pull weight up toward chest, squeeze shoulder blades, then lower.",
  "Bent Arm Barbell Pullover": "Lie on bench, hold barbell with bent arms. Lower weight behind head, stretch chest and lats, then pull back up.",
  "Bent Over Dumbbell Row": "Bend at hips, back flat. Pull a dumbbell to your hip, squeeze your back, then lower. Repeat other side.",
  "Bent Over Row": "Bend at hips, back flat. Grip barbell, pull to torso, squeeze shoulder blades, lower under control.",
  "Bicycle Crunch": "Lie on back, hands behind head. Bring opposite elbow to knee as you twist and pedal legs in the air, alternating sides.",
  "Bicep Curl": "",
  "Bird Dog": "Kneel on all fours. Extend opposite arm and leg straight, hold for a moment, then switch sides for the duration.",
  "Bodyweight Squat": "Stand feet slightly wide. Sit back and down like into a chair, keeping chest up, then drive back up.",
  "Bodyweight Calf Raise": "Lift heels off the ground while standing to strengthen calves.",
  "Bodyweight Concentration Curl": "Seated curl using self-resisted tension to target biceps.",
  "Bodyweight Good Morning": "Hinge at the hips with hands behind head to stretch and activate hamstrings and glutes.",
  "Bodyweight Kneeling Tricep Extension": "Use bodyweight and floor leverage to perform tricep extensions from a kneeling position.",
  "Bodyweight Lateral Raise": "Mimic dumbbell lateral raises using tension or support resistance to train side delts.",
  "Bodyweight Military Press": "Overhead pressing motion against the floor or wall to target shoulders with bodyweight.",
  "Bodyweight Overhead Tricep Extension": "Press body away from a surface overhead to target triceps using bodyweight.",
  "Bodyweight Tricep Extension": "Lower body toward hands from a plank position to isolate triceps.",
  "Box Jump": "Stand in front of box. Swing arms, bend knees, jump both feet onto box landing softly, then step back down.",
  "Box Squat": "Squat back onto a box or bench, pause briefly when seated, then drive up through your heels.",
  "Broad Jump": "Stand with feet hip-width. Swing arms and jump forward as far as possible, landing with control.",
  "Bulgarian Split Squat": "Stand a few feet from bench, place one foot behind you on it. Bend front knee to lower into lunge, then drive up.",
  "Burpees": "From standing, drop into a squat, kick feet back into push-up, perform a push-up, jump feet back, then explode up.",

  // C
"Cable Bent Over Row": "Hold cable handle with both hands, bend at hips, pull towards torso while keeping elbows close.",
"Cable Bicep Curl": "Stand facing cable, hold bar with palms up, curl toward shoulders while keeping elbows stationary.",
"Cable Chest Fly": "Stand between cables, arms extended, bring handles together in arc motion while squeezing chest.",
"Cable Chest Press": "Push cable handles forward from chest height, extending arms, keeping core tight and back straight.",
"Cable Crossover": "Stand between high cables, bring handles down and together in front of body in wide arc.",
"Cable Crunch": "Kneel facing cable machine, hold rope behind head, crunch forward to engage core.",
"Cable External Rotation": "Hold handle at elbow height, rotate arm outward to strengthen rotator cuff.",
"Cable Face Pull": "Pull rope towards face with elbows high, squeezing rear delts and upper back.",
"Cable Front Raise": "Lift handle in front of body to shoulder height, keeping arms straight and controlled.",
"Cable Hammer Curl": "Curl rope toward shoulders with palms facing each other, keeping elbows close to body.",
"Cable Internal Rotation": "Hold handle at elbow height, rotate arm inward to work rotator cuff.",
"Cable Kickback": "Extend arm behind body holding cable, keeping upper arm still to isolate triceps.",
"Cable Lateral Raise": "Raise cable handle sideways to shoulder level to target side delts.",
"Cable Leg Curl": "Attach strap to ankle, pull heel toward glutes while keeping upper leg still.",
"Cable Leg Extension": "With strap on ankle, extend leg forward to isolate quads.",
"Cable Overhead Tricep Extension": "Face away, grip rope, extend arms overhead to target triceps.",
"Cable Pull Through": "With rope between legs, hinge hips forward and squeeze glutes at top.",
"Cable Rear Delt Fly": "Hold handles crossed, pull out to sides in reverse fly motion to hit rear delts.",
"Cable Reverse Curl": "Curl bar with palms facing down to target brachialis and forearms.",
"Cable Reverse Fly": "Stand facing cable machine, pull handles apart in T-shape to hit rear delts.",
"Cable Reverse Wrist Curl": "Curl the cable handle upward with palms facing down to target wrist extensors.",
"Cable Rope Overhead Extension": "Grip rope behind head, extend arms to work long head of triceps.",
"Cable Shrug": "Hold handles at sides and shrug shoulders straight up, squeezing traps.",
"Cable Tricep Kickback": "Extend arm back while holding cable, keeping upper arm still to target triceps.",
"Cable Upright Row": "Pull bar or rope up to chest, keeping elbows higher than hands.",
"Cable Woodchopper": "Pull handle diagonally across body in chopping motion to work core and obliques.",
"Cable Wrist Curl": "Curl wrist up while holding cable bar to strengthen forearms.",
"Cable Y Raise": "Lift arms in Y shape using cables to hit front and side delts.",
"Calf Raises": "",
"Captain's Chair Knee Raise": "Support body on armrests, raise knees toward chest to target abs.",
"Captain's Chair Leg Raise": "Hang from chair, raise straight legs to hip height to hit lower abs.",
"Cheat Curl": "Use slight body momentum to lift heavier barbell curls, focusing on eccentric phase.",
"Chest Dip": "Lean forward during dip to engage chest more than triceps.",
"Chest Press": "Push bar or dumbbells away from chest, keeping back flat and elbows slightly flared.",
"Chest Press Machine": "Seated push motion using guided machine to target chest.",
"Chest Supported Dumbbell Row": "Lie face down on incline bench, row dumbbells toward ribs to hit mid-back.",
"Chest Supported Dumbbell Shrug": "While lying face down on incline, shrug shoulders up to target traps.",
"Chest Supported T Bar Row": "Use T-bar machine with chest pad for strict back isolation.",
"Chin Ups": "Pull body up with underhand grip until chin is over the bar.",
"Clamshells": "Lie on side with knees bent, open top knee while keeping feet together to activate glutes.",
"Clap Pull Ups": "Explosively pull up and clap hands before grabbing bar again.",
"Clap Push Ups": "Push up explosively from ground, clap hands mid-air and land back in push-up position.",
"Clean": "Lift barbell from ground to shoulders in one fluid motion, catching in front rack.",
"Clean and Jerk": "Perform clean, then drive bar overhead in jerk motion to complete Olympic lift.",
"Clean and Press": "Lift bar to shoulders (clean), then press overhead in controlled motion.",
"Clean High Pull": "Explosively pull bar to chest height with elbows high and outside.",
"Clean Pull": "Explosive lift pulling bar to mid-chest without full clean catch.",
"Close Grip Bench Press": "Bench press with narrow grip to emphasize triceps involvement.",
"Close Grip Dumbbell Bench Press": "Press dumbbells close together from chest to focus on triceps and inner chest.",
"Close Grip Incline Bench Press": "Incline press with narrow grip to target upper chest and triceps.",
"Close Grip Lat Pulldown": "Pull bar to chest with narrow grip, keeping elbows tucked.",
"Close Grip Pull Ups": "Pull body up using close grip to hit lower lats and biceps.",
"Close Grip Push Up": "Perform push-up with hands close together to target triceps.",
"Crossover Lunge": "Step one foot diagonally behind the other into deep lunge, keeping torso upright.",
"Cross Body Cable Tricep Extension": "Extend the arm across the body using a cable to isolate the long head of the triceps.",
"Cross Body Hammer Curl": "Curl dumbbells across the body with a neutral grip to target brachialis and biceps.",
"Cross Body Lat Pull Around": "Use a cable to pull from high to low across the body, engaging the lats in a sweeping arc.",
"Crunch": "Lie on back, curl upper torso toward knees while keeping lower back on floor.",
"Crunch Machine": "Use machine to curl torso forward against resistance, isolating abs.",
"Cycling": "Continuous pedaling motion to build endurance and leg strength.",

// D
"Dead Bug": "Lie on your back, lift arms and legs, and alternate extending opposite limbs while keeping core tight.",
"Dead Hang": "Hang from a pull-up bar with arms extended to build grip and shoulder strength.",
"Deadlift": "Lift a loaded barbell from the floor to standing by hinging at the hips and driving through the heels.",
"Decline Bench Press": "Press a barbell or dumbbells while lying on a decline bench to target the lower chest.",
"Decline Crunch": "Perform crunches on a decline bench to emphasize lower abs.",
"Decline Dumbbell Press": "Similar to decline bench press but using dumbbells for greater range and stability challenge.",
"Deficit Deadlift": "Stand on a platform to increase range of motion during deadlifts, targeting hamstrings and glutes.",
"Decline Dumbbell Fly": "Perform flys on a decline bench to target the lower portion of the chest.",
"Decline Push Ups": "Elevate feet to place more emphasis on upper chest and shoulders during push-ups.",
"Decline Pike Push Ups": "Perform pike push-ups with feet elevated to target shoulders and upper chest.",
"Decline Sit-Up": "Sit-up performed on a decline bench to increase abdominal activation.",
"Deficit Push Ups": "Perform push-ups with hands elevated on objects to increase range of motion.",
"Diamond Push Ups": "Push-up variation with hands close together forming a diamond shape to target triceps.",
"Double Crunch": "Simultaneously lift upper and lower body toward the center to activate entire core.",
"Dragon Flag": "Advanced core exercise lowering and raising body in a straight line from shoulders.",
"Dumbbell Bench Pull": "Row dumbbells while lying face down on a bench to isolate the upper back.",
"Dumbbell Calf Raise": "Hold dumbbells and raise heels off the floor to target calf muscles.",
"Dumbbell Clean and Press": "Explosively lift dumbbells to shoulders and press overhead in one fluid movement.",
"Dumbbell External Rotation": "Rotate dumbbell outward at 90° elbow flexion to strengthen rotator cuff.",
"Dumbbell Face Pull": "Pull dumbbells toward the face while externally rotating to target rear delts and upper traps.",
"Dumbbell Floor Press": "Press dumbbells from the floor to limit range and target chest and triceps.",
"Dumbbell Front Squat": "Hold dumbbells in front rack position and squat to strengthen quads and core.",
"Dumbbell Hang Clean": "From a hang position, explosively pull dumbbells to shoulders using hips and traps.",
"Dumbbell High Pull": "Pull dumbbells from hip height to chest using elbows high and wide to target traps and delts.",
"Dumbbell Incline Y Raise": "Raise dumbbells in a Y shape on an incline bench to isolate upper traps and rear delts.",
"Dumbbell Larsen Press": "Bench press dumbbells with feet off the ground to reduce leg drive and increase chest tension.",
"Dumbbell Push Press": "Use a small leg drive to press dumbbells overhead with power.",
"Dumbbell Reverse Curl": "Curl dumbbells with palms facing down to target brachialis and forearms.",
"Dumbbell Reverse Fly": "Bend forward and raise dumbbells to the side to train rear delts.",
"Dumbbell Reverse Wrist Curl": "Curl dumbbells upward with palms facing down to strengthen wrist extensors.",
"Dumbbell Side Bend": "Hold dumbbell on one side and bend sideways to target obliques.",
"Dumbbell Snatch": "Explosively lift dumbbell overhead in one motion using hips, shoulder, and core.",
"Dumbbell Spider Curl": "Perform curls while lying chest-down on an incline bench to isolate biceps.",
"Dumbbell Squat": "Hold dumbbells and perform squats to target quads, glutes, and hamstrings.",
"Dumbbell Tricep Kickback": "Extend dumbbells behind the body with elbows fixed to isolate triceps.",
"Dumbbell Upright Row": "Lift dumbbells vertically to chest height with elbows flared to hit traps and side delts.",
"Dumbbell Walking Calf Raise": "Walk while raising heels off the ground to train calves dynamically.",
"Dumbbell Wrist Curl": "Curl dumbbells upward with palms facing up to strengthen wrist flexors.",
"Dumbbell Bench Press": "Press dumbbells while lying flat to build chest, shoulders, and triceps.",
"Dumbbell Bulgarian Split Squat": "Lunge with rear foot elevated, holding dumbbells to target quads and glutes.",
"Dumbbell Clean": "Explosively lift dumbbells from floor to shoulder height, using hips and legs.",
"Dumbbell Concentration Curl": "Sit, rest elbow on thigh, and curl dumbbell to isolate biceps.",
"Dumbbell Bicep Curl": "Classic biceps exercise performed with dumbbells.",
"Dumbbell Deadlift": "Deadlift using dumbbells to build posterior chain with greater mobility.",
"Dumbbell Flyes": "Open and close arms with dumbbells on a bench to isolate the chest.",
"Dumbbell Front Raise": "Lift dumbbells in front of you to shoulder height to target front delts.",
"Dumbbell Hammer Curl": "Curl dumbbells with a neutral grip to target brachialis and forearms.",
"Incline Dumbbell Bench Press": "Press dumbbells on an incline bench to hit upper chest.",
"Dumbbell Lateral Raise": "Raise dumbbells out to the side to shoulder height to build the lateral delts.",
"Dumbbell Lunge": "Step forward or backward while holding dumbbells for lower body strength and balance.",
"Dumbbell Overhead Press": "Press dumbbells overhead from shoulder level to target delts and triceps.",
"Dumbbell Pullover": "Move a dumbbell from over your chest to behind your head to stretch chest and lats.",
"Dumbbell Romanian Deadlift": "Keep legs slightly bent and lower dumbbells down legs to target hamstrings and glutes.",
"Dumbbell Row": "Pull dumbbells toward the waist while bending over to work lats and upper back.",
"Dumbbell Shoulder Press": "Stand straight and press dumbbells from shoulder height straight overhead, then lower with control.",
"Dumbbell Shrug": "Lift shoulders up while holding dumbbells to target traps.",
"Dumbbell Skullcrusher": "Lie on a bench and extend dumbbells from forehead to target triceps.",
"Dumbbell Split Squat": "Lunge in place with one leg forward, dumbbells at sides.",
"Dumbbell Step Up": "Step onto a box or bench while holding dumbbells to target quads and glutes.",
"Dumbbell Thruster": "Perform a front squat and drive dumbbells overhead for full-body power.",
"Dumbbell Tricep Extension": "Extend dumbbells overhead to isolate triceps.",
"Dumbbell Z Press": "Sit on the floor and press dumbbells overhead for pure shoulder isolation with core stability.",
"Depth Jump": "Step off a box, land briefly, then jump vertically to build explosiveness.",
"Dip Machine": "Use a machine to assist or add resistance to triceps dips.",
"Dips": "Lower and raise your body on parallel bars, targeting triceps and chest.",
"Donkey Calf Raise": "Bend at hips with weight or partner on lower back, raise heels to target calves.",
"Double Under": "Jump rope exercise where the rope passes under your feet twice per jump.",
"Drag Curl": "Curl the bar while keeping elbows back to isolate the biceps.",

  // E
"Elbow to Knee Crunch": "Lie on your back, bring opposite elbow and knee together, alternating sides to work obliques.",
"Elliptical Trainer": "Low-impact cardio machine simulating walking or running with arm movement.",
"Elevated Push Up": "Perform push-ups with feet elevated to increase difficulty and shift emphasis to upper chest.",
"Explosive Push Up": "Push up with enough force to lift hands off ground for explosive power.",
"Explosive Squat Jump": "Perform a full squat followed by an explosive vertical jump for power training.",
"EZ Bar Lying Triceps Extension": "Lower the EZ bar to your forehead and extend to target triceps.",
"EZ Bar Preacher Curl": "Curl EZ bar over a preacher bench to isolate the biceps.",
"EZ Bar Spider Curl": "Curl EZ bar with chest supported on an incline bench for strict bicep targeting.",
"EZ Bar Curl": "Curl an EZ curl bar to target biceps with wrist-friendly grip.",
"EZ Bar Skullcrusher": "Lie on a bench and lower EZ bar to forehead, then extend arms to target triceps.",
"EZ Bar Upright Row": "Pull the EZ bar vertically to chest level with elbows high to target traps and lateral delts.",
"External Shoulder Rotation": "Use a band or light weight to rotate arm outward at elbow to strengthen rotator cuff.",

// F
"Face Pull": "Pull a rope attachment toward the face to target rear delts and upper back.",
"Feet Elevated Push Up": "Push-up variation with feet elevated to emphasize upper chest and shoulders.",
"Fingertip Push Up": "Push-ups performed on fingertips to build finger, wrist, and forearm strength.",
"Fire Hydrant": "Kneeling hip abduction exercise that targets glutes and outer thighs.",
"Floor Press": "Press weights from the floor to limit range and emphasize triceps.",
"Farmer's Walk": "Carry heavy weights in both hands while walking to build grip, core, and upper back strength.",
"Floor Hip Abduction": "Lie on your side and raise the top leg to target the hip abductors.",
"Floor Hip Extension": "Lie on your back and thrust hips upward to engage glutes and hamstrings.",
"Floor T Raise": "Lie face down and raise arms out to the sides in a 'T' to target rear delts.",
"Flutter Kick": "Lie on back and rapidly kick legs up and down to work lower abs.",
"Forward Lunge": "Step forward into a lunge, keeping chest up and knee over ankle.",
"Front Lever": "Gymnastic hold where body is held horizontally while hanging from a bar.",
"Front Raise": "Lift weight in front of you to shoulder level to isolate front delts.",
"Front Squat": "Barbell squat variation with bar held on front shoulders to target quads and core.",

// G
"GHD Back Extension": "Use GHD machine to bend at hips and raise torso to strengthen lower back and glutes.",
"GHD Sit Up": "Advanced sit-up performed on GHD machine for full range and core activation.",
"Glute Bridge": "Lie on back, drive through heels to lift hips and squeeze glutes.",
"Glute Ham Raise": "Lower body from kneeling to prone using hamstrings, then return to upright position.",
"Glute Kickback": "Extend one leg back and up from a quadruped position to isolate the glutes.",
"Goblet Squat": "Hold a dumbbell or kettlebell at chest and perform a squat with upright posture.",
"Good Morning": "Hinge at hips with barbell on back to target hamstrings and lower back.",
"Groin Stretch Lunge": "Lunge to the side or forward with focus on stretching groin muscles.",

// H
"Hack Squat": "Squat performed on a machine with back supported, targeting quads.",
"Hammer Curl": "Curl dumbbells with palms facing each other to work biceps and forearms.",
"Hammer Strength Chest Press": "Plate-loaded machine press mimicking dumbbell chest press movement.",
"Hammer Strength Row": "Use hammer strength machine to row with fixed path and loaded plates.",
"Hand Release Push Up": "Push-up variation where hands briefly lift off floor at bottom of each rep.",
"Handstand": "Hold body upside down vertically with hands on floor to build balance and shoulder strength.",
"Hack Squat Calf Raise": "Use a hack squat machine to perform calf raises by lifting heels while standing.",
"Half Kneeling One Arm Lat Pulldown": "Perform a single-arm lat pulldown from a half-kneeling stance for unilateral lat activation.",
"Half Squat": "Perform a partial squat to about halfway down, focusing on quads and glutes.",
"Hand Grippers": "Squeeze and hold hand grippers to build crushing grip strength.",
"Hanging Windshield Wipers": "Hang from a bar and move legs side-to-side to strengthen obliques and core.",
"Heel Touch": "Lie on your back and alternate touching your heels side to side to target obliques.",
"Heel-Elevated Squat": "Perform squats with heels elevated to emphasize quad activation.",
"Hex Bar Deadlift": "Use a trap bar to perform deadlifts with a more upright torso and reduced lower back strain.",
"Hex Bar Shrug": "Hold a trap bar and shrug shoulders upward to target upper traps.",
"High Plank": "Hold the top of a push-up position to build core and shoulder stability.",
"High Pulley Crunch": "Use a cable machine from above to crunch down and contract the abs.",
"High to Low Cable Fly": "Pull cables downward from high to low angles to emphasize lower chest.",
"Hip Extension": "Extend hips backward from a prone or kneeling position to target glutes and hamstrings.",
"Hip Thrust": "Thrust hips upward using a bench or platform to maximally activate the glutes.",
"Handstand Push Up": "Push-up performed while in handstand to build shoulders and triceps.",
"Hang Clean": "Olympic lift from hang position to shoulders using hips and arms explosively.",
"Hang Power Clean": "Hang clean caught in partial squat for power development.",
"Hang Snatch": "Explosively lift bar from hang to overhead in one motion, landing in partial squat.",
"Hanging Knee Raise": "Hang from bar and raise knees toward chest to work abs.",
"Hanging Leg Raise": "Raise straight legs while hanging from bar for lower ab and hip flexor strength.",
"High Pull Up": "Explosively pull barbell up to chest using hips and traps.",
"Hip Abduction Machine": "Push legs outward against resistance to work glute medius and abductors.",
"Hip Adduction Machine": "Squeeze legs together against resistance to target inner thighs.",
"Horizontal Leg Press": "Push platform away using legs while seated to target quads, glutes, and hamstrings.",

  // I
"Incline Bench Press": "Press dumbbells or barbell on an inclined bench focusing on upper chest.",
"Incline Dumbbell Curl": "Curl dumbbells while seated on an incline bench to isolate biceps.",
"Incline Push Up": "Perform push-ups with hands elevated to decrease difficulty and target lower chest.",
"Incline Cable Curl": "Sit back on an incline bench and curl cables to stretch and target the long head of the biceps.",
"Incline Dumbbell Fly": "Perform flys on an incline bench to target the upper chest.",
"Incline Hammer Curl": "Curl dumbbells with a neutral grip on an incline bench to train the brachialis and biceps.",
"Incline Machine Press": "Use a machine press at an incline angle to target the upper chest with stability.",
"Incline Side Lying Lateral Raise": "Lie sideways on an incline bench and raise dumbbell to isolate the medial delt.",
"Inverted Row": "Pull body up to bar while hanging underneath, targeting back and biceps.",
"Iron Cross": "Gymnastic hold on rings with arms extended laterally, building shoulder and chest strength.",

// J
"Jackknife Sit Up": "Lie on back and simultaneously raise legs and upper body to touch hands to feet.",
"Jammer Press": "Use a lever machine to press handles forward mimicking a chest press.",
"Jefferson Curl": "Slowly curl spine forward with barbell or weight to stretch hamstrings and back.",
"Jefferson Deadlift": "Deadlift variation straddling the bar with mixed grip to target posterior chain.",
"Jefferson Squat": "Straddle the bar and squat with a mixed grip to reduce spinal load and target quads and glutes.",
"Jerk": "Olympic lift where weight is explosively pushed overhead after a quick dip and drive.",
"Jump Rope": "Cardio exercise using a rope to jump repeatedly, improving coordination and endurance.",
"Jump Shrug": "Explosive shrug with jump, targeting traps and power development.",
"Jump Squat": "Squat followed by an explosive vertical jump to build power in legs.",
"Jumping Jacks": "Jump with legs and arms moving laterally to elevate heart rate and warm up the body.",

// K
"Kettlebell Clean": "Swing kettlebell to rack position using hips and arm movement for explosive power.",
"Kettlebell Deadlift": "Deadlift performed holding kettlebells to target posterior chain muscles.",
"Kettlebell Goblet Squat": "Hold kettlebell at chest and squat down keeping chest upright.",
"Kettlebell Snatch": "Explosive movement lifting kettlebell overhead in one motion.",
"Kettlebell Swing": "Hip hinge swinging kettlebell forward to chest height, working glutes and hamstrings.",
"Kettlebell Thruster": "Squat with kettlebell followed by overhead press in one fluid movement.",
"Kettlebell Turkish Get Up": "Complex full-body movement transitioning from lying to standing with kettlebell overhead.",
"Kipping Handstand Push Up": "Handstand push-up using momentum from hips to assist movement.",
"Kipping Pull Up": "Pull-up using hip and leg swing to generate momentum and increase reps.",
"Knee Cobra Push Ups": "Push-up variation from knees with elbows close to the body to target triceps and chest.",
"Knee Pike Push Ups": "Kneeling pike push-up to emphasize shoulder development with less load.",
"Knee Push Ups": "Push-up performed from the knees for reduced resistance and beginner-friendly scaling.",
"Knee Raise": "Lift knees towards chest from hanging or seated position to work lower abs.",
"Knees to Elbows": "From hanging position, raise knees to touch elbows to target core and hip flexors.",
"Kneeling Finger Press": "Press up from the floor using your fingers while kneeling to build finger and wrist strength.",
"Kneeling Fist to Palm": "Shift hand pressure from a fist to palm position for wrist mobility and control.",
"Knuckle Push Ups": "Push-up done on knuckles to increase wrist stability and simulate combat conditioning.",

// L
"L Pull Up": "Pull up while holding legs straight out in front forming an 'L' shape to increase core activation.",
"Landmine Press": "Press one end of barbell fixed in landmine attachment to work shoulders and chest.",
"Landmine Row": "Row movement with one end of barbell in landmine setup targeting back muscles.",
"Lat Pulldown": "Pull bar down towards chest on machine to target latissimus dorsi muscles.",
"Lateral Box Jump": "Jump sideways onto a box to improve lateral power and coordination.",
"Lateral Lunge": "Step out to the side into a deep lunge to target glutes and inner thighs.",
"Lawnmower Row": "Single-arm row pulling weight from low position diagonally upward like starting a lawnmower.",
"Leg Curl": "Curl legs towards buttocks on machine to isolate hamstrings.",
"Leg Extension": "Extend legs on machine to isolate quadriceps muscles.",
"Leg Press": "Push platform away using legs on machine to work quads, glutes, and hamstrings.",
"Leg Press Calf Raise": "Use a leg press machine to perform calf raises by pressing through your toes.",
"Lying Leg Raises": "Lie flat and lift legs vertically to strengthen lower abs.",
"Lunges": "Step forward or backward into a bent knee position to work legs and glutes.",
"L Sit": "Hold your legs extended straight in front of you while supporting your body on your hands to train core and hip flexors.",
"Landmine Squat": "Hold one end of a barbell in front of the chest and squat down to target quads with added stability.",
"Larsen Press": "Bench press variation performed with legs off the floor to remove leg drive and increase upper body focus.",
"Low Plank": "Hold a plank position on forearms to develop core strength and endurance.",
"Low to High Cable Fly": "Raise cables from low to high to target the upper chest and front delts.",
"Lying Cable Curl": "Lie on a bench and curl the cable from behind the head to isolate the biceps.",
"Lying Dumbbell Tricep Extension": "Extend dumbbells from behind the head while lying down to hit the triceps long head.",
"Lying Leg Curl": "Use a machine to curl legs while lying face down to target hamstrings.",
"Lying Tricep Extension": "Lower and extend a barbell or dumbbells from behind the head to work the triceps.",

  // M
"Machine Bicep Curl": "Curl weight using a bicep curl machine to isolate biceps.",
"Machine Chest Press": "Press handles forward on machine mimicking bench press movement.",
"Machine Fly": "Bring handles together on fly machine to work chest muscles.",
"Machine Back Extension": "Extend the torso upward against resistance on a machine to strengthen the lower back.",
"Machine Calf Press": "Press the weight using your toes on a leg press machine to isolate the calves.",
"Machine Calf Raise": "Use a calf raise machine to lift heels upward and train calf muscles.",
"Machine Chest Fly": "Perform flys with arms pressing inward on a machine to isolate the chest.",
"Machine Glute Kickback": "Kick back against resistance on a machine to isolate glute activation.",
"Machine High Row": "Pull handles down and back on a high-row machine to target upper and mid-back.",
"Machine Hip Thrust": "Use a hip thrust machine to press hips upward and develop glute strength.",
"Machine Lateral Raise": "Raise arms sideways on machine targeting side delts.",
"Machine Shoulder Press": "Press weights overhead on machine to work shoulder muscles.",
"Machine Shrug": "Shrug shoulders against resistance on machine to target traps.",
"Machine Pullover": "Use a pullover machine to bring arms from overhead to hips, targeting the lats.",
"Machine Reverse Fly": "Pull arms apart on a reverse fly machine to strengthen rear delts and upper back.",
"Machine Row": "Row the handles of a machine toward your torso to build upper back thickness.",
"Machine Seated Crunch": "Use a crunch machine to contract your abs while seated for isolated core work.",
"Machine Tricep Extension": "Extend arms against resistance on a triceps machine to isolate the triceps.",
"Meadows Row": "Row a barbell from a landmine setup with a side grip to train lats and rear delts unilaterally.",
"Military Press": "Overhead barbell press performed standing to develop shoulders and triceps.",
"Muscle Snatch": "Pull a barbell from floor to overhead in one motion without rebending the knees, emphasizing upper back and traps.",
"Medicine Ball Slam": "Lift and slam a medicine ball to the ground to develop power and core strength.",
"Mountain Climbers": "From plank position, alternate driving knees to chest rapidly for cardio and core.",
"Muscle Up": "Pull up and transition over bar into a dip position to work full upper body.",

// N
"Narrow Grip Bench Press": "Bench press with hands close together to target triceps and inner chest.",
"Narrow Grip Push Up": "Push-ups with hands close under chest to emphasize triceps.",
"Neck Curl": "Lie on back and flex neck upward to strengthen neck flexors.",
"Neck Extension": "Extend neck backward against resistance to strengthen neck extensors.",
"Neck Flexion": "Forward neck movement strengthening the front neck muscles.",
"Neck Lateral Flexion": "Side bending of neck to work lateral neck muscles.",
"Neck Rotation": "Rotate neck side to side to strengthen and mobilize cervical spine.",
"Negative Chin Up": "Lower yourself slowly from top of chin-up to build strength.",
"Negative Pull Up": "Slow eccentric lowering phase of pull-up to build pulling strength.",
"Neutral Grip Lat Pulldown": "Pull a neutral grip handle downward to target the lats with a more joint-friendly angle.",
"Neutral Grip Chin Up": "Chin-up performed with palms facing each other for balanced arm and back activation.",
"Neutral Grip Pull Up": "Pull-up with palms facing each other to reduce shoulder strain.",
"Nordic Curl": "Kneeling hamstring curl with feet anchored, lowering torso forward slowly.",
"No Equipment Air Bike": "Simulated air bike motion without a machine, pedaling legs and moving arms for cardio.",

// O
"One Arm Band Row": "Pull a resistance band with one arm focusing on back muscles.",
"One Arm Barbell Row": "Row a barbell with one arm to target the lats and mid-back.",
"One Arm Cable Curl": "Curl a cable handle with one arm to isolate the biceps.",
"One Arm Cable Extension": "Extend one arm using cable machine to work triceps.",
"One Arm Cable Fly": "Perform a chest fly motion with one arm on cable machine.",
"One Arm Seated Cable Row": "Row one arm on cable machine targeting back muscles.",
"One Arm Chest Press": "Press a dumbbell or handle with one arm to strengthen chest.",
"One Arm Clean": "Explosive lift of a weight from ground to shoulder with one arm.",
"One Arm Deadlift": "Deadlift a weight using one arm focusing on posterior chain.",
"One Arm Dumbbell Bench Press": "Press dumbbell with one arm while lying on bench.",
"One Arm Dumbbell Curl": "Curl a dumbbell with one arm targeting biceps.",
"One Arm Dumbbell Fly": "Perform a chest fly lying down using one dumbbell arm.",
"One Arm Dumbbell Lateral Raise": "Raise one dumbbell to side to target shoulder delts.",
"One Arm Dumbbell Overhead Press": "Press dumbbell overhead with one arm for shoulder strength.",
"One Arm Dumbbell Pullover": "Lie on bench and pull dumbbell over chest with one arm.",
"One Arm Dumbbell Row": "Row dumbbell with one arm to strengthen upper back.",
"One Arm Dumbbell Shrug": "Raise one shoulder shrugging a dumbbell to work traps.",
"One Arm Dumbbell Triceps Extension": "Extend dumbbell overhead with one arm to target triceps.",
"One Arm Floor Press": "Press dumbbell from floor with one arm focusing on triceps.",
"One Arm Cable Front Raise": "Raise a cable handle forward one arm at a time to isolate the front delts.",
"One Arm Dumbbell Preacher Curl": "Curl a dumbbell over a preacher bench with one arm to isolate the biceps.",
"One Arm Landmine Press": "Press the end of a landmine bar overhead with one arm to target the shoulders.",
"One Arm Lat Pulldown": "Perform lat pulldown with one arm at a time to address imbalances and increase lat focus.",
"One Arm Machine Reverse Fly": "Use the reverse fly machine one arm at a time to target the rear delts and traps.",
"One Arm Pull Up": "Perform a pull-up using one arm for maximal upper body pulling strength.",
"One Arm Kettlebell Clean": "Explosively lift kettlebell from ground to shoulder with one arm.",
"One Arm Kettlebell Deadlift": "Deadlift kettlebell with one arm to engage hamstrings and back.",
"One Arm Kettlebell Row": "Row kettlebell with one arm targeting lats.",
"One Arm Push Up": "Perform a push up using one arm to increase chest and core challenge.",
"One Arm Row (Machine)": "Row using machine one arm at a time for controlled back training.",
"One Arm Smith Machine Row": "Row one arm on Smith machine to target upper back.",
"One Arm Turkish Get Up": "Full-body movement rising from ground holding weight overhead with one arm.",
"Open Chain Cable Row": "Cable row without foot support to emphasize back muscles.",
"Overhead Cable Curl": "Curl cables from overhead with arms outstretched to emphasize the short head of the biceps.",
"Overhead Dumbbell Press": "Press dumbbells overhead to strengthen deltoids.",
"Overhead Lunge": "Perform a lunge while holding weight overhead to engage core and legs.",
"Overhead Medicine Ball Slam": "Raise medicine ball overhead and slam it down for explosive power.",
"Overhead Plate Carry": "Hold weight plate overhead while walking to challenge shoulders and core.",
"Overhead Rope Extension": "Extend rope overhead on cable machine to target triceps.",
"Overhead Squat": "Squat holding barbell overhead to build mobility and strength.",
"Overhead Tricep Extension": "Extend arms overhead with weight to target triceps.",
"Overhead Walk": "Walk carrying weight overhead for shoulder and core stability.",
"Overhead Y Raise": "Raise arms overhead in a Y shape to strengthen upper back and shoulders.",

// P
"Pallof Press": "Anti-rotation core exercise pressing band or cable straight out.",
"Pause Deadlift": "Pause at the shin during the deadlift to improve power off the floor and reinforce technique.",
"Pause Squat": "Squat and hold at the bottom position briefly to build control and strength in the hole.",
"Paused Bench Press": "Pause at the bottom of the bench press to eliminate momentum and increase strength off the chest.",
"Paused Incline Bench Press": "Pause at the bottom of an incline bench press to emphasize upper chest control and drive.",
"Pendulum Squat": "Use a pendulum squat machine for a guided squat motion targeting the quads deeply.",
"Pilates": "Low-impact bodyweight movements focusing on core strength, stability, and flexibility.",
"Pin Squat": "Squat from a dead stop on pins to build power and technique at a specific sticking point.",
"Pistol Squat": "Perform a single-leg squat with the opposite leg extended straight forward to build balance and strength.",
"Planche": "Hold your body parallel to the ground using only hands, requiring extreme upper body and core strength.",
"Pec Deck Fly": "Chest fly movement on pec deck machine to isolate pectorals.",
"Pendlay Row": "Barbell row from floor with strict form to target upper back.",
"Physio Ball Crunch": "Crunch performed lying on stability ball to engage abs deeply.",
"Pike Push Up": "Push up with hips elevated to emphasize shoulders.",
"Piriformis Stretch": "Stretch targeting piriformis muscle to relieve hip tightness.",
"Plank": "Hold body in straight line on forearms to build core stability.",
"Plank to Push Up": "Transition from plank position to push up for core and upper body.",
"Plate Curl": "Curl a weight plate to strengthen forearms and biceps.",
"Plate Front Raise": "Raise weight plate in front to shoulder height for front delts.",
"Plate Pinch Hold": "Pinch weight plates together and hold to build grip strength.",
"Power Clean": "Explosive Olympic lift from floor to shoulders for total body power.",
"Power Snatch": "Explosive Olympic lift from floor to overhead in one motion.",
"Preacher Curl": "Curl performed on preacher bench isolating the biceps.",
"Prone Y Raise": "Raise arms overhead lying prone in a Y shape to strengthen back.",
"Pull Over": "Lie on bench and lower weight from chest over head to work lats.",
"Pull-Ups": "Hang from bar and pull body up to chin above bar.",
"Push Jerk": "Explosive overhead press with dip and drive using legs.",
"Push Press": "Overhead press using leg drive for power.",
"Push-Up": "Bodyweight press-up to strengthen chest, shoulders, and triceps.",
"Planche Push Up": "Perform a push-up with your body leaned forward, feet off the floor, requiring extreme shoulder and core strength.",
"Plank Lean": "Hold a plank position while leaning forward to increase shoulder and core loading.",
"Preacher Hammer Curl": "Use a neutral grip to curl on a preacher bench, emphasizing brachialis and forearms.",
"Press Around": "Use cables to press across the body in a wide arc, targeting chest and delts.",
"Pseudo Planche Push Up": "Push-up with hands low and body leaned forward to simulate planche training.",

  // Q
"Quad Extension": "Extend knees using machine to isolate quadriceps.",
"Quadruped Shoulder Tap": "From all fours, tap opposite shoulder to engage core and shoulders.",

// R
"Rack Pull": "Partial deadlift from rack or blocks focusing on lockout.",
"Rear Delt Fly": "Raise weights to sides focusing on rear shoulder delts.",
"Renegade Row": "Row dumbbell while holding plank position for back and core.",
"Reverse Crunch": "Lift hips off floor towards chest focusing on lower abs.",
"Reverse Curl": "Curl barbell or dumbbells with palms facing down for forearms.",
"Reverse Fly": "Raise arms to sides while bent over targeting rear delts.",
"Reverse Hyperextension": "Lie face down and raise legs behind to strengthen lower back.",
"Reverse Lunge": "Step backward into lunge to engage glutes and quads.",
"Ring Dip": "Dip performed on gymnastic rings requiring stability and strength.",
"Ring Muscle Up": "Pull up and push up combined on rings for advanced upper body.",
"Ring Push Up": "Push up on gymnastic rings to challenge stability.",
"Rope Climb": "Climb a rope using arms and legs for full body workout.",
"Rope Face Pull": "Pull rope towards face to target rear delts and traps.",
"Rope Hammer Curl": "Curl rope attachment focusing on biceps and forearms.",
"Rowing Machine": "Cardio machine simulating rowing for full body endurance.",
"Russian Twist": "Seated torso twists with or without weight to target obliques.",
"Reverse EZ Bar Curl": "Curl the EZ bar with palms down to target brachialis and forearms.",
"Reverse Grip Bench Press": "Bench press with an underhand grip to shift emphasis to upper chest and triceps.",
"Reverse Grip Bent Over Row": "Row the barbell with an underhand grip to increase bicep and lat involvement.",
"Reverse Grip Lat Pulldown": "Use an underhand grip on the lat pulldown to target lower lats and biceps.",
"Reverse Grip Push Up": "Push-up with fingers pointing toward your feet to increase bicep and wrist engagement.",
"Reverse Grip Tricep Pushdown": "Push down on the cable with a supinated grip to emphasize the medial head of the triceps.",
"Reverse Nordic Curl": "Lean back slowly while keeping hips extended to stretch and strengthen quads eccentrically.",
"Reverse Plank": "Hold a plank with your chest facing upward to target posterior chain and shoulder stabilizers.",
"Reverse Wrist Curl": "Curl wrists upward with palms facing down to train wrist extensors.",
"Roman Chair Side Bend": "Bend sideways on a Roman chair to isolate and strengthen the obliques.",
"Romanian Deadlift": "",

// S
"Scissor Kick": "Lie on back and move legs side to side rapidly for abs.",
"Seated Calf Raise": "Raise heels while seated to target calf muscles.",
"Seated Cable Row": "Row cable machine seated to strengthen back muscles.",
"Seated Leg Curl": "Curl legs while seated to work hamstrings.",
"Seated Overhead Press": "Press weights overhead seated to isolate shoulders.",
"Seated Row": "Row on machine while seated targeting mid-back.",
"Shoulder Press": "",
"Side Lateral Raise": "Raise arms laterally to shoulder height to target side delts.",
"Side Plank": "Hold body sideways on forearm to engage obliques and core.",
"Single Arm Cable Row": "Row cable with one arm to target back muscles.",
"Single Arm Dumbbell Press": "Press dumbbell overhead with one arm to strengthen shoulders.",
"Single Arm Row": "Row dumbbell with one arm focusing on lats and traps.",
"Single Leg Deadlift": "Deadlift on one leg to challenge balance and hamstrings.",
"Single Leg Glute Bridge": "Glute bridge performed on one leg for isolated glute work.",
"Single Leg Press": "Leg press machine used with one leg to target quads and glutes.",
"Sit Up": "Abdominal exercise lifting torso from lying to seated position.",
"Skater Squat": "Single leg squat performed by crossing one leg behind the other.",
"Skullcrusher": "Lying triceps extension lowering bar or dumbbells to forehead.",
"Sled Push": "Push weighted sled across surface to build strength and power.",
"Side Crunch": "Lie on your side and crunch upward to isolate the obliques.",
"Side Leg Raise": "Lift your top leg while lying on your side to target hip abductors.",
"Side Lunge": "Step laterally into a lunge to target glutes, quads, and inner thighs.",
"Side Lying Hip Adduction": "Lift your bottom leg while lying on your side to target the inner thigh.",
"Single Arm Hammer Curl": "Perform a hammer curl one arm at a time with a neutral grip for brachialis and forearm development.",
"Single Arm Tricep Pushdown": "Use a cable to extend one arm downward, isolating the triceps unilaterally.",
"Single Leg Dumbbell Deadlift": "Hinge at the hips on one leg while holding dumbbells to target hamstrings and glutes.",
"Single Leg Extension": "Extend one leg at a time using a leg extension machine to isolate the quads.",
"Single Leg Lying Leg Curl": "Perform leg curls one leg at a time while lying face down to target hamstrings.",
"Single Leg Romanian Deadlift": "Hinge on one leg with dumbbells or barbell to stretch and strengthen the posterior chain.",
"Single Leg Seated Calf Raise": "Perform seated calf raises one leg at a time to improve balance and calf symmetry.",
"Single Leg Squat": "Perform squats on one leg to develop balance and strength in the quads and glutes.",
"Sissy Squat": "Lean back while squatting to shift emphasis entirely to the quads.",
"Smith Machine Bench Press": "Use the Smith machine to press the bar from your chest, targeting pecs and triceps with added stability.",
"Smith Machine Bent Over Row": "Row the barbell in a Smith machine while bent over to isolate upper back and lats.",
"Smith Machine Bulgarian Split Squat": "Use the Smith machine for guided Bulgarian split squats to target quads and glutes unilaterally.",
"Smith Machine Calf Raise": "Stand under the Smith bar and raise heels off the ground to train calves.",
"Smith Machine Incline Bench Press": "Use the Smith machine at an incline to focus on upper chest development.",
"Smith Machine Reverse Grip Bent Over Row": "Use an underhand grip in the Smith machine to row and target lats and biceps.",
"Smith Machine Shoulder Press": "Press the bar overhead in a Smith machine to develop deltoids with guided movement.",
"Smith Machine Shrug": "Use a Smith machine to shrug shoulders upward and train the traps.",
"Smith Machine Sissy Squat": "Lean back in the Smith machine to perform quad-dominant sissy squats safely.",
"Smith Machine Squat": "Use the Smith machine for squats with added balance support to target the legs and glutes.",
"Snatch Pull": "Pull a barbell explosively from the floor to hip height to train the snatch's power phase.",
"Snatch": "Olympic lift pulling barbell from ground to overhead in one motion.",
"Snatch Grip Deadlift": "Deadlift with wide grip to target upper back and traps.",
"Snow Angel": "Lie face down moving arms and legs like making a snow angel.",
"Split Squat": "Lunge-like squat with back foot elevated to increase difficulty.",
"Split Squat Jump": "Explosive jump from split squat position to develop power.",
"Spider Curl": "Curl dumbbells or a barbell while lying face down on an incline bench to isolate the biceps.",
"Split Jerk": "Drive a barbell overhead and split legs to catch it in a stable position, developing explosive power.",
"Spoto Press": "Pause the bench press slightly above the chest to eliminate momentum and build pressing strength.",
"Standing Cable Crunch": "Crunch downward from a standing position using a high cable to target the abs.",
"Standing Machine Lateral Raise": "Use a machine while standing to lift arms to the side and target the lateral delts.",
"Squat": "Basic lower body movement bending knees and hips to stand up.",
"Squat Jump": "Explosive jump starting from squat position to improve power.",
"Stair Climber": "Cardio machine simulating stair stepping for endurance.",
"Standing Calf Raise": "Raise heels while standing to strengthen calves.",
"Standing Cable Row": "Row cable while standing to target back muscles.",
"Standing Leg Curl": "Curl leg backward while standing to work hamstrings.",
"Standing Leg Raise": "Lift leg to side or front to strengthen hips and core.",
"Step Up": "Step onto raised platform to strengthen legs and glutes.",
"Step Up with Knee Raise": "Step onto platform then raise opposite knee for core work.",
"Stiff Leg Deadlift": "Deadlift variation focusing on hamstrings with straight legs.",
"Straight Arm Pulldown": "Pull cable down with straight arms to target lats.",
"Strict Curl": "Biceps curl performed with strict form and no body sway.",
"Strict Press": "Overhead press performed standing with no leg drive.",
"Sumo Deadlift": "Deadlift with wide stance targeting inner thighs and glutes.",
"Sumo Squat": "Squat with wide stance to emphasize inner thighs and glutes.",
"Superman": "Lie face down and lift arms and legs simultaneously to strengthen lower back.",
"Safety Bar Squat": "Use a safety squat bar to squat with a more upright torso and reduced shoulder strain.",
"Seated Dip Machine": "Use a dip machine while seated to press downward and target the triceps.",
"Seated Dumbbell Curl": "Curl dumbbells while seated to focus on strict bicep contraction.",
"Seated Dumbbell Shoulder Press": "Press dumbbells overhead while seated to target the shoulders.",
"Seated Dumbbell Tricep Extension": "Extend dumbbell overhead with both hands while seated to target the triceps long head.",
"Seated Hammer Curl": "Use a neutral grip to curl dumbbells while seated, emphasizing the brachialis.",
"Seated Shoulder Press": "Use a barbell or dumbbells to press overhead from a seated position, isolating shoulders.",
"Seated Smith Machine Shoulder Press": "Press the bar upward in a Smith machine from a seated position to isolate shoulders with stability.",
"Shoulder Pin Press": "Start the bar from pins at forehead height to press overhead and strengthen the sticking point.",

// T
"Table Inverted Row": "Pull your chest up to a table or low bar while hanging underneath to train the back.",
"Tate Press": "Lower dumbbells toward the chest with elbows flared and press back up to target the triceps uniquely.",
"Tiger Bend Push Ups": "Push-up variant combining a forearm plank to push-up movement for triceps and shoulders.",
"Toes to Bar": "Hang from a bar and lift toes to touch it, training the entire core dynamically.",
"Torso Rotation Machine": "Twist your torso against resistance while seated to target the obliques and core.",
"T Bar Row": "Row using T-bar apparatus to target middle back.",
"Towel Pull Up": "Pull up gripping towels to increase grip strength challenge.",
"Tricep Dips": "Dip targeting triceps performed on parallel bars or bench.",
"Triceps Extension": "Extend the barbell overhead or lying down to isolate the triceps.",
"Triceps Kickback": "Extend arms back to isolate triceps muscle.",
"Tricep Pushdown": "Push cable downward targeting triceps.",
"Triceps Rope Pushdown": "Push rope downward on cable machine targeting triceps.",
"Trap Bar Deadlift": "Deadlift using trap bar for balanced weight distribution.",
"Tree Pose": "Balance pose standing on one leg to improve stability.",
"Turkish Get Up": "Full body movement rising from ground holding weight overhead.",

  // U
  "Upright Row": "Pull barbell or dumbbells up to chin to target traps and delts.",
  "Upright Shoulder Raise": "Raise shoulders upward to strengthen traps.",
  "Uttanasana (Forward Bend)": "Standing forward fold to stretch hamstrings and lower back.",

  // V
  "V Squat": "Use a V-squat machine to perform a guided squat with more back support and quad focus.",
  "V Ups": "Simultaneously lift legs and torso into a 'V' shape to contract the abs.",
  "Vertical Leg Press": "Press weight vertically upward using a leg press machine to train quads and glutes.",
  "Vertical Traction Machine": "Use a vertical machine to pull weight downward, mimicking a lat pulldown.",
  "Viking Press": "Use a Viking press attachment to drive the handles upward, emphasizing shoulders.",
  "V Sit": "Balance seated on buttocks with legs and torso forming a V shape.",
  "Vertical Jump": "Jump vertically to test and train leg power.",
  "Volleyball Serve": "Overhand or underhand serve movement to develop shoulder power.",

  // W
  "Wall Ball Shot": "Throw medicine ball against wall and catch for power and endurance.",
  "Wall Sit": "Sit against wall with knees bent to build leg endurance.",
  "Walking Lunge": "Perform lunges while moving forward to strengthen legs and balance.",
  "Water Rowing": "Rowing machine using water resistance for cardio and strength.",
  "Weighted Pull Up": "Pull up with added weight to increase difficulty.",
  "Wide Grip Lat Pulldown": "Pull bar down to chest with wide grip to target lats.",
  "Waiter Curl": "Curl a single dumbbell held vertically under the plates to emphasize the biceps peak.",
  "Wall Push Up": "Push away from a wall to perform a beginner-friendly push-up with reduced intensity.",
  "Wide Grip Bench Press": "Use a wide grip on the barbell to emphasize chest activation during the bench press.",
  "Wide Grip Chest Press": "Use a chest press machine with a wide grip to target outer chest fibers.",
  "Wide Grip Push Up": "Push-up with hands set wider than shoulder width to focus on chest involvement.",
  "Wide Grip Seated Cable Row": "Use a wide grip on a seated cable row to target the upper back and rear delts.",
  "Wide Grip Pull Up": "Pull up with wide grip focusing on lats.",
  "Windmill": "Rotate torso and touch foot with opposite hand for flexibility and strength.",
  "Wrist Curl": "Curl wrist upward or downward to strengthen forearms.",

  // X
  "X Band Walk": "Side step with resistance band around legs to activate hip abductors.",

  // Y
  "Y Raise": "Raise arms overhead in Y position lying prone to strengthen upper back.",
  "Yoke Walk": "Carry heavy frame on shoulders while walking for total body strength.",
  "Yates Row": "Row a barbell with an underhand grip and slight torso lean to target the lower lats and traps.",

  // Z
  "Z Press": "Seated overhead press performed with legs extended on floor.",
  "Zercher Deadlift": "Deadlift the barbell from a low height using a Zercher hold to build posterior chain and core." ,
  "Zottman Curl": "Curl with palms up and lower with palms down to train both biceps and forearms.",
  "Zercher Squat": "Squat holding barbell in crook of elbows to target quads and core.",
};