export const EXERCISE_EQUIPMENT = {

  // --- A ---
  "Ab Wheel Rollout": "bodyweight",
  "Abcoaster": "machine",
  "Air Bike": "cardio",
  "Archer Pull Ups": "bodyweight",
  "Archer Push Ups": "bodyweight",
  "Arnold Press": "dumbbell",
  "Assisted Chin Ups": "machine",
  "Assisted Dips": "machine",
  "Assisted Muscle Ups": "band",
  "Assisted Pull Ups": "machine",

  // --- B ---
  "Back Extension": "bodyweight",
  "Back Lever": "bodyweight",
  "Balance Board Squat": "bodyweight",
  "Band Assisted Pull Ups": "band",
  "Barbell Calf Raise": "barbell",
  "Barbell Clean": "barbell",
  "Barbell Concentration Curl": "barbell",
  "Barbell Curl": "barbell",
  "Barbell Flexion Row": "barbell",
  "Barbell Front Raise": "barbell",
  "Barbell Glute Bridge": "barbell",
  "Barbell Hack Squat": "barbell",
  "Barbell Lunge": "barbell",
  "Barbell Overhead Press": "barbell",
  "Barbell Power Shrug": "barbell",
  "Barbell Pullover": "barbell",
  "Barbell Reverse Curl": "barbell",
  "Barbell Reverse Lunge": "barbell",
  "Barbell Row": "barbell",
  "Barbell Shrug": "barbell",
  "Barbell Step Up": "barbell",
  "Barbell Thruster": "barbell",
  "Barbell Upright Row": "barbell",
  "Barbell Z Press": "barbell",
  "Bayesian Curl": "cable",
  "Behind the Back Deadlift": "barbell",
  "Behind the Back Neck Press": "barbell",
  "Behind the Back Barbell Shrug": "barbell",
  "Behind the Neck Press": "barbell",
  "Bench Dips": "bodyweight",
  "Bench Pin Press": "barbell",
  "Bench Press": "barbell",
  "Bench Pull": "barbell",
  "Bent Arm Barbell Pullover": "barbell",
  "Bent Over Dumbbell Row": "dumbbell",
  "Bent Over Row": "barbell",
  "Bicycle Crunch": "bodyweight",
  "Bicep Curl": "barbell",
  "Bird Dog": "bodyweight",
  "Bodyweight Squat": "bodyweight",
  "Bodyweight Calf Raise": "bodyweight",
  "Bodyweight Concentration Curl": "bodyweight",
  "Bodyweight Good Morning": "bodyweight",
  "Bodyweight Kneeling Tricep Extension": "bodyweight",
  "Bodyweight Lateral Raise": "bodyweight",
  "Bodyweight Military Press": "bodyweight",
  "Bodyweight Overhead Tricep Extension": "bodyweight",
  "Bodyweight Tricep Extension": "bodyweight",
  "Box Jump": "bodyweight",
  "Box Squat": "barbell",
  "Broad Jump": "bodyweight",
  "Bulgarian Split Squat": "dumbbell",
  "Burpees": "bodyweight",

  // --- C ---
  "Cable Bent Over Row": "cable",
  "Cable Bicep Curl": "cable",
  "Cable Chest Fly": "cable",
  "Cable Chest Press": "cable",
  "Cable Crossover": "cable",
  "Cable Crunch": "cable",
  "Cable External Rotation": "cable",
  "Cable Face Pull": "cable",
  "Cable Front Raise": "cable",
  "Cable Hammer Curl": "cable",
  "Cable Internal Rotation": "cable",
  "Cable Kickback": "cable",
  "Cable Lateral Raise": "cable",
  "Cable Leg Curl": "cable",
  "Cable Leg Extension": "cable",
  "Cable Overhead Tricep Extension": "cable",
  "Cable Pull Through": "cable",
  "Cable Rear Delt Fly": "cable",
  "Cable Reverse Curl": "cable",
  "Cable Reverse Fly": "cable",
  "Cable Reverse Wrist Curl": "cable",
  "Cable Rope Overhead Extension": "cable",
  "Cable Shrug": "cable",
  "Cable Tricep Kickback": "cable",
  "Cable Upright Row": "cable",
  "Cable Woodchopper": "cable",
  "Cable Wrist Curl": "cable",
  "Cable Y Raise": "cable",
  "Calf Raises": "machine",
  "Captain's Chair Knee Raise": "machine",
  "Captain's Chair Leg Raise": "machine",
  "Cheat Curl": "barbell",
  "Chest Dip": "bodyweight",
  "Chest Press": "dumbbell",
  "Chest Press Machine": "machine",
  "Chest Supported Dumbbell Row": "dumbbell",
  "Chest Supported Dumbbell Shrug": "dumbbell",
  "Chest Supported T Bar Row": "machine",
  "Chin Ups": "bodyweight",
  "Clamshells": "bodyweight",
  "Clap Pull Ups": "bodyweight",
  "Clap Push Ups": "bodyweight",
  "Clean": "barbell",
  "Clean and Jerk": "barbell",
  "Clean and Press": "barbell",
  "Clean High Pull": "barbell",
  "Clean Pull": "barbell",
  "Close Grip Bench Press": "barbell",
  "Close Grip Dumbbell Bench Press": "dumbbell",
  "Close Grip Incline Bench Press": "barbell",
  "Close Grip Lat Pulldown": "cable",
  "Close Grip Pull Ups": "bodyweight",
  "Close Grip Push Up": "bodyweight",
  "Crossover Lunge": "dumbbell",
  "Cross Body Cable Tricep Extension": "cable",
  "Cross Body Hammer Curl": "dumbbell",
  "Cross Body Lat Pull Around": "cable",
  "Crunch": "bodyweight",
  "Crunch Machine": "machine",
  "Cycling": "cardio",

  // --- D ---
  "Dead Bug": "bodyweight",
  "Dead Hang": "bodyweight",
  "Deadlift": "barbell",
  "Decline Bench Press": "barbell",
  "Decline Crunch": "bodyweight",
  "Decline Dumbbell Press": "dumbbell",
  "Deficit Deadlift": "barbell",
  "Decline Dumbbell Fly": "dumbbell",
  "Decline Push Ups": "bodyweight",
  "Decline Pike Push Ups": "bodyweight",
  "Decline Sit-Up": "bodyweight",
  "Deficit Push Ups": "bodyweight",
  "Diamond Push Ups": "bodyweight",
  "Double Crunch": "bodyweight",
  "Dragon Flag": "bodyweight",
  "Dumbbell Bench Pull": "dumbbell",
  "Dumbbell Calf Raise": "dumbbell",
  "Dumbbell Clean and Press": "dumbbell",
  "Dumbbell External Rotation": "dumbbell",
  "Dumbbell Face Pull": "dumbbell",
  "Dumbbell Floor Press": "dumbbell",
  "Dumbbell Front Squat": "dumbbell",
  "Dumbbell Hang Clean": "dumbbell",
  "Dumbbell High Pull": "dumbbell",
  "Dumbbell Incline Y Raise": "dumbbell",
  "Dumbbell Larsen Press": "dumbbell",
  "Dumbbell Push Press": "dumbbell",
  "Dumbbell Reverse Curl": "dumbbell",
  "Dumbbell Reverse Fly": "dumbbell",
  "Dumbbell Reverse Wrist Curl": "dumbbell",
  "Dumbbell Side Bend": "dumbbell",
  "Dumbbell Snatch": "dumbbell",
  "Dumbbell Spider Curl": "dumbbell",
  "Dumbbell Squat": "dumbbell",
  "Dumbbell Tricep Kickback": "dumbbell",
  "Dumbbell Upright Row": "dumbbell",
  "Dumbbell Walking Calf Raise": "dumbbell",
  "Dumbbell Wrist Curl": "dumbbell",
  "Dumbbell Bench Press": "dumbbell",
  "Dumbbell Bulgarian Split Squat": "dumbbell",
  "Dumbbell Clean": "dumbbell",
  "Dumbbell Concentration Curl": "dumbbell",
  "Dumbbell Bicep Curl": "dumbbell",
  "Dumbbell Deadlift": "dumbbell",
  "Dumbbell Flyes": "dumbbell",
  "Dumbbell Front Raise": "dumbbell",
  "Dumbbell Hammer Curl": "dumbbell",
  "Incline Dumbbell Bench Press": "dumbbell",
  "Dumbbell Lateral Raise": "dumbbell",
  "Dumbbell Lunge": "dumbbell",
  "Dumbbell Overhead Press": "dumbbell",
  "Dumbbell Pullover": "dumbbell",
  "Dumbbell Romanian Deadlift": "dumbbell",
  "Dumbbell Row": "dumbbell",
  "Dumbbell Shoulder Press": "dumbbell",
  "Dumbbell Shrug": "dumbbell",
  "Dumbbell Skullcrusher": "dumbbell",
  "Dumbbell Split Squat": "dumbbell",
  "Dumbbell Step Up": "dumbbell",
  "Dumbbell Thruster": "dumbbell",
  "Dumbbell Tricep Extension": "dumbbell",
  "Dumbbell Z Press": "dumbbell",
  "Depth Jump": "bodyweight",
  "Dip Machine": "machine",
  "Dips": "bodyweight",
  "Donkey Calf Raise": "machine",
  "Double Under": "cardio",
  "Drag Curl": "barbell",

  // --- E ---
  "Elbow to Knee Crunch": "bodyweight",
  "Elliptical Trainer": "cardio",
  "Elevated Push Up": "bodyweight",
  "Explosive Push Up": "bodyweight",
  "Explosive Squat Jump": "bodyweight",
  "EZ Bar Lying Triceps Extension": "barbell",
  "EZ Bar Preacher Curl": "barbell",
  "EZ Bar Spider Curl": "barbell",
  "EZ Bar Curl": "barbell",
  "EZ Bar Skullcrusher": "barbell",
  "EZ Bar Upright Row": "barbell",
  "External Shoulder Rotation": "bodyweight",

  // --- F ---
  "Face Pull": "cable",
  "Feet Elevated Push Up": "bodyweight",
  "Fingertip Push Up": "bodyweight",
  "Fire Hydrant": "bodyweight",
  "Floor Press": "barbell",
  "Farmer's Walk": "carry",
  "Floor Hip Abduction": "bodyweight",
  "Floor Hip Extension": "bodyweight",
  "Floor T Raise": "bodyweight",
  "Flutter Kick": "bodyweight",
  "Forward Lunge": "dumbbell",
  "Front Lever": "bodyweight",
  "Front Raise": "dumbbell",
  "Front Squat": "barbell",

  // --- G ---
  "GHD Back Extension": "machine",
  "GHD Sit Up": "machine",
  "Glute Bridge": "bodyweight",
  "Glute Ham Raise": "machine",
  "Glute Kickback": "bodyweight",
  "Goblet Squat": "kettlebell",
  "Good Morning": "barbell",
  "Groin Stretch Lunge": "bodyweight",

  // --- H ---
  "Hack Squat": "machine",
  "Hammer Curl": "dumbbell",
  "Hammer Strength Chest Press": "machine",
  "Hammer Strength Row": "machine",
  "Hand Release Push Up": "bodyweight",
  "Handstand": "bodyweight",
  "Hack Squat Calf Raise": "machine",
  "Half Kneeling One Arm Lat Pulldown": "cable",
  "Half Squat": "barbell",
  "Hand Grippers": "gripper",
  "Hanging Windshield Wipers": "bodyweight",
  "Heel Touch": "bodyweight",
  "Heel-Elevated Squat": "barbell",
  "Hex Bar Deadlift": "trapbar",
  "Hex Bar Shrug": "trapbar",
  "High Plank": "bodyweight",
  "High Pulley Crunch": "cable",
  "High to Low Cable Fly": "cable",
  "Hip Extension": "machine",
  "Hip Thrust": "barbell",
  "Handstand Push Up": "bodyweight",
  "Hang Clean": "barbell",
  "Hang Power Clean": "barbell",
  "Hang Snatch": "barbell",
  "Hanging Knee Raise": "bodyweight",
  "Hanging Leg Raise": "bodyweight",
  "High Pull Up": "bodyweight",
  "Hip Abduction Machine": "machine",
  "Hip Adduction Machine": "machine",
  "Horizontal Leg Press": "machine",

  // --- I ---
  "Incline Bench Press": "barbell",
  "Incline Dumbbell Curl": "dumbbell",
  "Incline Push Up": "bodyweight",
  "Incline Cable Curl": "cable",
  "Incline Dumbbell Fly": "dumbbell",
  "Incline Hammer Curl": "dumbbell",
  "Incline Machine Press": "machine",
  "Incline Side Lying Lateral Raise": "dumbbell",
  "Inverted Row": "bodyweight",
  "Iron Cross": "bodyweight",

  // --- J ---
  "Jackknife Sit Up": "bodyweight",
  "Jammer Press": "machine",
  "Jefferson Curl": "barbell",
  "Jefferson Deadlift": "barbell",
  "Jefferson Squat": "barbell",
  "Jerk": "barbell",
  "Jump Rope": "cardio",
  "Jump Shrug": "barbell",
  "Jump Squat": "bodyweight",
  "Jumping Jacks": "bodyweight",

  // --- K ---
  "Kettlebell Clean": "kettlebell",
  "Kettlebell Deadlift": "kettlebell",
  "Kettlebell Goblet Squat": "kettlebell",
  "Kettlebell Snatch": "kettlebell",
  "Kettlebell Swing": "kettlebell",
  "Kettlebell Thruster": "kettlebell",
  "Kettlebell Turkish Get Up": "kettlebell",
  "Kipping Handstand Push Up": "bodyweight",
  "Kipping Pull Up": "bodyweight",
  "Knee Cobra Push Ups": "bodyweight",
  "Knee Pike Push Ups": "bodyweight",
  "Knee Push Ups": "bodyweight",
  "Knee Raise": "bodyweight",
  "Knees to Elbows": "bodyweight",
  "Kneeling Finger Press": "bodyweight",
  "Kneeling Fist to Palm": "bodyweight",
  "Knuckle Push Ups": "bodyweight",

  // --- L ---
  "L Pull Up": "bodyweight",
  "Landmine Press": "landmine",
  "Landmine Row": "landmine",
  "Lat Pulldown": "cable",
  "Lateral Box Jump": "bodyweight",
  "Lateral Lunge": "dumbbell",
  "Lawnmower Row": "dumbbell",
  "Leg Curl": "machine",
  "Leg Extension": "machine",
  "Leg Press": "machine",
  "Leg Press Calf Raise": "machine",
  "Lying Leg Raises": "bodyweight",
  "Lunges": "dumbbell",
  "L Sit": "bodyweight",
  "Landmine Squat": "landmine",
  "Larsen Press": "barbell",
  "Low Plank": "bodyweight",
  "Low to High Cable Fly": "cable",
  "Lying Cable Curl": "cable",
  "Lying Dumbbell Tricep Extension": "dumbbell",
  "Lying Leg Curl": "machine",
  "Lying Tricep Extension (Skull Crushers)": "barbell",

  // --- M ---
  "Machine Bicep Curl": "machine",
  "Machine Chest Press": "machine",
  "Machine Fly": "machine",
  "Machine Back Extension": "machine",
  "Machine Calf Press": "machine",
  "Machine Calf Raise": "machine",
  "Machine Chest Fly": "machine",
  "Machine Glute Kickback": "machine",
  "Machine High Row": "machine",
  "Machine Hip Thrust": "machine",
  "Machine Lateral Raise": "machine",
  "Machine Shoulder Press": "machine",
  "Machine Shrug": "machine",
  "Machine Tricep Extension": "machine",
  "Machine Pullover": "machine",
  "Machine Reverse Fly": "machine",
  "Machine Row": "machine",
  "Machine Seated Crunch": "machine",
  "Meadows Row": "landmine",
  "Military Press": "barbell",
  "Muscle Snatch": "barbell",
  "Medicine Ball Slam": "medicineBall",
  "Mountain Climbers": "bodyweight",
  "Muscle Up": "bodyweight",

  // --- N ---
  "Narrow Grip Bench Press": "barbell",
  "Narrow Grip Push Up": "bodyweight",
  "Neck Curl": "bodyweight",
  "Neck Extension": "bodyweight",
  "Neck Flexion": "bodyweight",
  "Neck Lateral Flexion": "bodyweight",
  "Neck Rotation": "bodyweight",
  "Negative Chin Up": "bodyweight",
  "Negative Pull Up": "bodyweight",
  "Neutral Grip Lat Pulldown": "cable",
  "Neutral Grip Chin Up": "bodyweight",
  "Neutral Grip Pull Up": "bodyweight",
  "Nordic Curl": "bodyweight",
  "No Equipment Air Bike": "bodyweight",

    // --- O ---
  "One Arm Band Row": "band",
  "One Arm Barbell Row": "barbell",
  "One Arm Cable Curl": "cable",
  "One Arm Cable Extension": "cable",
  "One Arm Cable Fly": "cable",
  "One Arm Seated Cable Row": "cable",
  "One Arm Chest Press": "dumbbell",
  "One Arm Clean": "barbell",
  "One Arm Deadlift": "barbell",
  "One Arm Dumbbell Bench Press": "dumbbell",
  "One Arm Dumbbell Curl": "dumbbell",
  "One Arm Dumbbell Fly": "dumbbell",
  "One Arm Dumbbell Lateral Raise": "dumbbell",
  "One Arm Dumbbell Overhead Press": "dumbbell",
  "One Arm Dumbbell Pullover": "dumbbell",
  "One Arm Dumbbell Row": "dumbbell",
  "One Arm Dumbbell Shrug": "dumbbell",
  "One Arm Dumbbell Triceps Extension": "dumbbell",
  "One Arm Floor Press": "dumbbell",
  "One Arm Cable Front Raise": "cable",
  "One Arm Dumbbell Preacher Curl": "dumbbell",
  "One Arm Landmine Press": "landmine",
  "One Arm Lat Pulldown": "cable",
  "One Arm Machine Reverse Fly": "machine",
  "One Arm Pull Up": "bodyweight",
  "One Arm Kettlebell Clean": "kettlebell",
  "One Arm Kettlebell Deadlift": "kettlebell",
  "One Arm Kettlebell Row": "kettlebell",
  "One Arm Push Up": "bodyweight",
  "One Arm Row (Machine)": "machine",
  "One Arm Smith Machine Row": "machine",
  "One Arm Turkish Get Up": "kettlebell",
  "Open Chain Cable Row": "cable",
  "Overhead Cable Curl": "cable",
  "Overhead Dumbbell Press": "dumbbell",
  "Overhead Lunge": "dumbbell",
  "Overhead Medicine Ball Slam": "medicineBall",
  "Overhead Plate Carry": "plate",
  "Overhead Rope Extension": "cable",
  "Overhead Squat": "barbell",
  "Overhead Tricep Extension": "barbell",
  "Overhead Walk": "dumbbell",
  "Overhead Y Raise": "dumbbell",

  // --- P ---
  "Pallof Press": "cable",
  "Pause Deadlift": "barbell",
  "Pause Squat": "barbell",
  "Paused Bench Press": "barbell",
  "Paused Incline Bench Press": "barbell",
  "Pendulum Squat": "machine",
  "Pilates": "bodyweight",
  "Pin Squat": "barbell",
  "Pistol Squat": "bodyweight",
  "Planche": "bodyweight",
  "Pec Deck Fly": "machine",
  "Pendlay Row": "barbell",
  "Physio Ball Crunch": "stabilityBall",
  "Pike Push Up": "bodyweight",
  "Piriformis Stretch": "stretch",
  "Plank": "bodyweight",
  "Plank to Push Up": "bodyweight",
  "Plate Curl": "plate",
  "Plate Front Raise": "plate",
  "Plate Pinch Hold": "plate",
  "Power Clean": "barbell",
  "Power Snatch": "barbell",
  "Preacher Curl": "barbell",
  "Prone Y Raise": "dumbbell",
  "Pull Over": "barbell",
  "Pull-Ups": "bodyweight",
  "Push Jerk": "barbell",
  "Push Press": "barbell",
  "Push-Up": "bodyweight",
  "Planche Push Up": "bodyweight",
  "Plank Lean": "bodyweight",
  "Preacher Hammer Curl": "dumbbell",
  "Press Around": "cable",
  "Pseudo Planche Push Up": "bodyweight",

  // --- Q ---
  "Quad Extension": "machine",
  "Quadruped Shoulder Tap": "bodyweight",

  // --- R ---
  "Rack Pull": "barbell",
  "Rear Delt Fly": "dumbbell",
  "Renegade Row": "dumbbell",
  "Reverse Crunch": "bodyweight",
  "Reverse Curl": "barbell",
  "Reverse Fly": "dumbbell",
  "Reverse Hyperextension": "machine",
  "Reverse Lunge": "dumbbell",
  "Ring Dip": "rings",
  "Ring Muscle Up": "rings",
  "Ring Push Up": "rings",
  "Rope Climb": "rope",
  "Rope Face Pull": "cable",
  "Rope Hammer Curl": "cable",
  "Rowing Machine": "cardio",
  "Russian Twist": "bodyweight",
  "Reverse EZ Bar Curl": "barbell",
  "Reverse Grip Bench Press": "barbell",
  "Reverse Grip Bent Over Row": "barbell",
  "Reverse Grip Lat Pulldown": "cable",
  "Reverse Grip Push Up": "bodyweight",
  "Reverse Grip Tricep Pushdown": "cable",
  "Reverse Nordic Curl": "bodyweight",
  "Reverse Plank": "bodyweight",
  "Reverse Wrist Curl": "barbell",
  "Roman Chair Side Bend": "machine",
  "Romanian Deadlift": "barbell",

  // --- S ---
  "Scissor Kick": "bodyweight",
  "Seated Calf Raise": "machine",
  "Seated Cable Row": "cable",
  "Seated Leg Curl": "machine",
  "Seated Overhead Press": "barbell",
  "Seated Row": "machine",
  "Shoulder Press": "barbell",
  "Side Lateral Raise": "dumbbell",
  "Side Plank": "bodyweight",
  "Single Arm Cable Row": "cable",
  "Single Arm Dumbbell Press": "dumbbell",
  "Single Arm Row": "dumbbell",
  "Single Leg Deadlift": "dumbbell",
  "Single Leg Glute Bridge": "bodyweight",
  "Single Leg Press": "machine",
  "Sit Up": "bodyweight",
  "Skater Squat": "bodyweight",
  "Skullcrusher": "barbell",
  "Sled Push": "sled",
  "Side Crunch": "bodyweight",
  "Side Leg Raise": "bodyweight",
  "Side Lunge": "dumbbell",
  "Side Lying Hip Adduction": "bodyweight",
  "Single Arm Hammer Curl": "dumbbell",
  "Single Arm Tricep Pushdown": "cable",
  "Single Leg Dumbbell Deadlift": "dumbbell",
  "Single Leg Extension": "machine",
  "Single Leg Lying Leg Curl": "machine",
  "Single Leg Romanian Deadlift": "dumbbell",
  "Single Leg Seated Calf Raise": "machine",
  "Single Leg Squat": "bodyweight",
  "Sissy Squat": "machine",
  "Smith Machine Bench Press": "machine",
  "Smith Machine Bent Over Row": "machine",
  "Smith Machine Bulgarian Split Squat": "machine",
  "Smith Machine Calf Raise": "machine",
  "Smith Machine Incline Bench Press": "machine",
  "Smith Machine Reverse Grip Bent Over Row": "machine",
  "Smith Machine Shoulder Press": "machine",
  "Smith Machine Shrug": "machine",
  "Smith Machine Sissy Squat": "machine",
  "Smith Machine Squat": "machine",
  "Snatch Pull": "barbell",
  "Snatch": "barbell",
  "Snatch Grip Deadlift": "barbell",
  "Snow Angel": "bodyweight",
  "Split Squat": "dumbbell",
  "Split Squat Jump": "bodyweight",
  "Spider Curl": "dumbbell",
  "Split Jerk": "barbell",
  "Spoto Press": "barbell",
  "Standing Cable Crunch": "cable",
  "Standing Machine Lateral Raise": "machine",
  "Squat": "barbell",
  "Squat Jump": "bodyweight",
  "Stair Climber": "cardio",
  "Standing Calf Raise": "bodyweight",
  "Standing Cable Row": "cable",
  "Standing Leg Curl": "machine",
  "Standing Leg Raise": "bodyweight",
  "Step Up": "dumbbell",
  "Step Up with Knee Raise": "dumbbell",
  "Stiff Leg Deadlift": "barbell",
  "Straight Arm Pulldown": "cable",
  "Strict Curl": "barbell",
  "Strict Press": "barbell",
  "Sumo Deadlift": "barbell",
  "Sumo Squat": "barbell",
  "Superman": "bodyweight",
  "Safety Bar Squat": "barbell",
  "Seated Dip Machine": "machine",
  "Seated Dumbbell Curl": "dumbbell",
  "Seated Dumbbell Shoulder Press": "dumbbell",
  "Seated Dumbbell Tricep Extension": "dumbbell",
  "Seated Hammer Curl": "dumbbell",
  "Seated Shoulder Press": "barbell",
  "Seated Smith Machine Shoulder Press": "machine",
  "Shoulder Pin Press": "barbell",

  // --- T ---
  "Table Inverted Row": "bodyweight",
  "Tate Press": "dumbbell",
  "Tiger Bend Push Ups": "bodyweight",
  "Toes to Bar": "bodyweight",
  "Torso Rotation Machine": "machine",
  "T Bar Row": "barbell",
  "Towel Pull Up": "bodyweight",
  "Tricep Dips": "bodyweight",
  "Tricep Extension": "barbell",
  "Tricep Kickback": "dumbbell",
  "Tricep Pushdown": "cable",
  "Tricep Rope Pushdown": "cable",
  "Trap Bar Deadlift": "trapbar",
  "Tree Pose": "bodyweight",
  "Turkish Get Up": "kettlebell",

  // --- U ---
  "Upright Row": "barbell",
  "Upright Shoulder Raise": "barbell",
  "Uttanasana (Forward Bend)": "bodyweight",

  // --- V ---
  "V Squat": "machine",
  "V Ups": "bodyweight",
  "Vertical Leg Press": "machine",
  "Vertical Traction Machine": "machine",
  "Viking Press": "barbell",
  "V Sit": "bodyweight",
  "Vertical Jump": "bodyweight",
  "Volleyball Serve": "bodyweight",

  // --- W ---
  "Wall Ball Shot": "medicineBall",
  "Wall Sit": "bodyweight",
  "Walking Lunge": "dumbbell",
  "Water Rowing": "cardio",
  "Weighted Pull Up": "bodyweight",
  "Wide Grip Lat Pulldown": "cable",
  "Waiter Curl": "dumbbell",
  "Wall Push Up": "bodyweight",
  "Wide Grip Bench Press": "barbell",
  "Wide Grip Chest Press": "machine",
  "Wide Grip Push Up": "bodyweight",
  "Wide Grip Seated Cable Row": "cable",
  "Wide Grip Pull Up": "bodyweight",
  "Windmill": "kettlebell",
  "Wrist Curl": "barbell",

  // --- X ---
  "X Band Walk": "band",

  // --- Y ---
  "Y Raise": "dumbbell",
  "Yoke Walk": "carry",
  "Yates Row": "barbell",

  // --- Z ---
  "Z Press": "barbell",
  "Zercher Deadlift": "barbell",
  "Zottman Curl": "dumbbell",
  "Zercher Squat": "barbell",
};