export const MUSCLE_GROUPS = {
    
  // A
  "Ab Wheel Rollout": ["core"],
  "Abcoaster": ["core"],
  "Air Bike": ["cardio", "core"],
  "Archer Pull Ups": ["lats", "biceps"],
  "Archer Push Ups": ["chest", "triceps", "shoulders"],
  "Arnold Press": ["shoulders", "triceps"],
  "Assisted Chin Ups": ["lats", "biceps"],
  "Assisted Dips": ["triceps", "chest"],
  "Assisted Muscle Ups": ["lats", "chest", "triceps", "shoulders"],
  "Assisted Pull Ups": ["lats", "biceps"],

  // B
  "Back Extension": ["lower back", "glutes"],
  "Back Lever": ["core", "lats", "shoulders"],
  "Balance Board Squat": ["quads", "glutes", "core"],
  "Band Assisted Pull Ups": ["lats", "biceps"],
  "Barbell Calf Raise": ["calves"],
  "Barbell Clean": ["full body", "quads", "glutes", "traps"],
  "Barbell Concentration Curl": ["biceps"],
  "Barbell Curl": ["biceps"],
  "Barbell Flexion Row": ["biceps", "lats"],
  "Barbell Front Raise": ["shoulders"],
  "Barbell Glute Bridge": ["glutes", "hamstrings"],
  "Barbell Hack Squat": ["quads", "glutes"],
  "Barbell Lunge": ["quads", "glutes", "hamstrings"],
  "Barbell Overhead Press": ["shoulders", "triceps"],
  "Barbell Power Shrug": ["traps"],
  "Barbell Pullover": ["chest", "lats"],
  "Barbell Reverse Curl": ["biceps", "forearms"],
  "Barbell Reverse Lunge": ["quads", "glutes", "hamstrings"],
  "Barbell Row": ["lats", "rhomboids", "traps"],
  "Barbell Shrug": ["traps"],
  "Barbell Step Up": ["quads", "glutes"],
  "Barbell Thruster": ["quads", "glutes", "shoulders", "triceps"],
  "Barbell Upright Row": ["traps", "shoulders"],
  "Barbell Z Press": ["shoulders", "triceps", "core"],
  "Bayesian Curl": ["biceps"],
  "Behind the Back Deadlift": ["hamstrings", "glutes", "lower back"],
  "Behind the Back Neck Press": ["shoulders", "triceps"],
  "Behind the Back Barbell Shrug": ["traps"],
  "Behind the Neck Press": ["shoulders", "triceps"],
  "Bench Dips": ["triceps", "chest"],
  "Bench Pin Press": ["chest", "triceps"],
  "Bench Press": ["chest", "triceps", "shoulders"],
  "Bench Pull": ["lats", "rhomboids", "traps"],
  "Bent Arm Barbell Pullover": ["chest", "lats"],
  "Bent Over Dumbbell Row": ["lats", "traps"],
  "Bent Over Row": ["lats", "traps", "rhomboids"],
  "Bicycle Crunch": ["core"],
  "Bicep Curl": ["biceps"],
  "Bird Dog": ["core", "lower back"],
  "Bodyweight Squat": ["quads", "glutes", "hamstrings"],
  "Bodyweight Calf Raise": ["calves"],
  "Bodyweight Concentration Curl": ["biceps"],
  "Bodyweight Good Morning": ["hamstrings", "glutes", "lower back"],
  "Bodyweight Kneeling Tricep Extension": ["triceps"],
  "Bodyweight Lateral Raise": ["shoulders"],
  "Bodyweight Military Press": ["shoulders", "triceps"],
  "Bodyweight Overhead Tricep Extension": ["triceps"],
  "Bodyweight Tricep Extension": ["triceps"],
  "Box Jump": ["quads", "glutes", "hamstrings", "calves"],
  "Box Squat": ["quads", "glutes", "hamstrings"],
  "Broad Jump": ["quads", "glutes", "hamstrings", "calves"],
  "Bulgarian Split Squat": ["quads", "glutes", "hamstrings"],
  "Burpees": ["full body", "cardio"],

  // C
  "Cable Bent Over Row": ["lats", "traps", "rhomboids"],
  "Cable Bicep Curl": ["biceps"],
  "Cable Chest Fly": ["chest"],
  "Cable Chest Press": ["chest", "triceps", "shoulders"],
  "Cable Crossover": ["chest"],
  "Cable Crunch": ["core"],
  "Cable External Rotation": ["rotator cuff"],
  "Cable Face Pull": ["rear delts", "traps"],
  "Cable Front Raise": ["shoulders"],
  "Cable Hammer Curl": ["biceps", "forearms"],
  "Cable Internal Rotation": ["rotator cuff"],
  "Cable Kickback": ["triceps"],
  "Cable Lateral Raise": ["shoulders"],
  "Cable Leg Curl": ["hamstrings"],
  "Cable Leg Extension": ["quads"],
  "Cable Overhead Tricep Extension": ["triceps"],
  "Cable Pull Through": ["glutes", "hamstrings"],
  "Cable Rear Delt Fly": ["rear delts"],
  "Cable Reverse Curl": ["biceps", "forearms"],
  "Cable Reverse Fly": ["rear delts"],
  "Cable Reverse Wrist Curl": ["forearms"],
  "Cable Rope Overhead Extension": ["triceps"],
  "Cable Shrug": ["traps"],
  "Cable Tricep Kickback": ["triceps"],
  "Cable Upright Row": ["traps", "shoulders"],
  "Cable Woodchopper": ["core", "obliques"],
  "Cable Wrist Curl": ["forearms"],
  "Cable Y Raise": ["shoulders"],
  "Calf Raises": ["calves"],
  "Captain's Chair Knee Raise": ["abs", "hip flexors"],
  "Captain's Chair Leg Raise": ["abs", "hip flexors"],
  "Cheat Curl": ["biceps"],
  "Chest Dip": ["chest", "triceps"],
  "Chest Press": ["chest", "triceps", "shoulders"],
  "Chest Press Machine": ["chest", "triceps"],
  "Chest Supported Dumbbell Row": ["lats", "traps"],
  "Chest Supported Dumbbell Shrug": ["traps"],
  "Chest Supported T Bar Row": ["lats", "traps"],
  "Chin Ups": ["lats", "biceps"],
  "Clamshells": ["glutes"],
  "Clap Pull Ups": ["lats", "biceps"],
  "Clap Push Ups": ["chest", "triceps"],
  "Clean": ["full body", "quads", "traps", "glutes"],
  "Clean and Jerk": ["full body", "legs", "traps", "shoulders"],
  "Clean and Press": ["full body", "legs", "traps", "shoulders"],
  "Clean High Pull": ["traps", "delts"],
  "Clean Pull": ["hamstrings", "glutes", "traps"],
  "Close Grip Bench Press": ["triceps", "chest"],
  "Close Grip Dumbbell Bench Press": ["triceps", "chest"],
  "Close Grip Incline Bench Press": ["triceps", "upper chest"],
  "Close Grip Lat Pulldown": ["lats", "biceps"],
  "Close Grip Pull Ups": ["lats", "biceps"],
  "Close Grip Push Up": ["triceps", "chest"],
  "Crossover Lunge": ["quads", "glutes"],
  "Cross Body Cable Tricep Extension": ["triceps"],
  "Cross Body Hammer Curl": ["biceps", "forearms"],
  "Cross Body Lat Pull Around": ["lats"],
  "Crunch": ["core"],
  "Crunch Machine": ["core"],
  "Cycling": ["cardio", "legs"],

  // D
  "Dead Bug": ["core"],
  "Dead Hang": ["grip", "shoulders"],
  "Deadlift": ["hamstrings", "glutes", "lower back"],
  "Decline Bench Press": ["lower chest", "triceps"],
  "Decline Crunch": ["abs"],
  "Decline Dumbbell Press": ["lower chest", "triceps"],
  "Deficit Deadlift": ["hamstrings", "glutes"],
  "Decline Dumbbell Fly": ["lower chest"],
  "Decline Push Ups": ["upper chest", "triceps"],
  "Decline Pike Push Ups": ["shoulders"],
  "Decline Sit-Up": ["abs"],
  "Deficit Push Ups": ["chest", "triceps"],
  "Diamond Push Ups": ["triceps", "chest"],
  "Double Crunch": ["core"],
  "Dragon Flag": ["core"],
  "Dumbbell Bench Pull": ["lats", "traps"],
  "Dumbbell Calf Raise": ["calves"],
  "Dumbbell Clean and Press": ["full body", "legs", "shoulders"],
  "Dumbbell External Rotation": ["rotator cuff"],
  "Dumbbell Face Pull": ["rear delts"],
  "Dumbbell Floor Press": ["chest", "triceps"],
  "Dumbbell Front Squat": ["quads", "core"],
  "Dumbbell Hang Clean": ["traps", "legs"],
  "Dumbbell High Pull": ["traps", "shoulders"],
  "Dumbbell Incline Y Raise": ["rear delts", "traps"],
  "Dumbbell Larsen Press": ["chest"],
  "Dumbbell Push Press": ["shoulders", "triceps", "legs"],
  "Dumbbell Reverse Curl": ["biceps", "forearms"],
  "Dumbbell Reverse Fly": ["rear delts"],
  "Dumbbell Reverse Wrist Curl": ["forearms"],
  "Dumbbell Side Bend": ["obliques"],
  "Dumbbell Snatch": ["full body"],
  "Dumbbell Spider Curl": ["biceps"],
  "Dumbbell Squat": ["quads", "glutes"],
  "Dumbbell Tricep Kickback": ["triceps"],
  "Dumbbell Upright Row": ["traps", "shoulders"],
  "Dumbbell Walking Calf Raise": ["calves"],
  "Dumbbell Wrist Curl": ["forearms"],
  "Dumbbell Bench Press": ["chest", "triceps"],
  "Dumbbell Bulgarian Split Squat": ["quads", "glutes"],
  "Dumbbell Clean": ["full body"],
  "Dumbbell Concentration Curl": ["biceps"],
  "Dumbbell Bicep Curl": ["biceps"],
  "Dumbbell Deadlift": ["hamstrings", "glutes"],
  "Dumbbell Flyes": ["chest"],
  "Dumbbell Front Raise": ["shoulders"],
  "Dumbbell Hammer Curl": ["biceps", "forearms"],
  "Incline Dumbbell Bench Press": ["chest"],
  "Dumbbell Lateral Raise": ["shoulders"],
  "Dumbbell Lunge": ["quads", "glutes"],
  "Dumbbell Overhead Press": ["shoulders", "triceps"],
  "Dumbbell Pullover": ["chest", "lats"],
  "Dumbbell Romanian Deadlift": ["hamstrings", "glutes"],
  "Dumbbell Row": ["lats", "traps"],
  "Dumbbell Shoulder Press": ["shoulders", "triceps"],
  "Dumbbell Shrug": ["traps"],
  "Dumbbell Skullcrusher": ["triceps"],
  "Dumbbell Split Squat": ["quads", "glutes"],
  "Dumbbell Step Up": ["quads", "glutes"],
  "Dumbbell Thruster": ["legs", "shoulders"],
  "Dumbbell Tricep Extension": ["triceps"],
  "Dumbbell Z Press": ["shoulders", "core"],
  "Depth Jump": ["quads", "calves"],
  "Dip Machine": ["triceps", "chest"],
  "Dips": ["triceps", "chest"],
  "Donkey Calf Raise": ["calves"],
  "Double Under": ["cardio", "calves"],
  "Drag Curl": ["biceps"],

  // E
  "Elbow to Knee Crunch": ["core", "obliques"],
  "Elliptical Trainer": ["cardio"],
  "Elevated Push Up": ["upper chest", "triceps"],
  "Explosive Push Up": ["chest", "triceps"],
  "Explosive Squat Jump": ["quads", "glutes", "hamstrings"],
  "EZ Bar Lying Triceps Extension": ["triceps"],
  "EZ Bar Preacher Curl": ["biceps"],
  "EZ Bar Spider Curl": ["biceps"],
  "EZ Bar Curl": ["biceps"],
  "EZ Bar Skullcrusher": ["triceps"],
  "EZ Bar Upright Row": ["traps", "shoulders"],
  "External Shoulder Rotation": ["rotator cuff"],

  // F
  "Face Pull": ["rear delts", "traps"],
  "Feet Elevated Push Up": ["chest", "triceps"],
  "Fingertip Push Up": ["forearms", "chest"],
  "Fire Hydrant": ["glutes"],
  "Floor Press": ["chest", "triceps"],
  "Farmer's Walk": ["forearms", "core", "traps"],
  "Floor Hip Abduction": ["glutes"],
  "Floor Hip Extension": ["glutes", "hamstrings"],
  "Floor T Raise": ["rear delts"],
  "Flutter Kick": ["lower abs"],
  "Forward Lunge": ["quads", "glutes"],
  "Front Lever": ["core", "lats"],
  "Front Raise": ["shoulders"],
  "Front Squat": ["quads", "glutes"],

  // G
  "GHD Back Extension": ["hamstrings", "glutes", "lower back"],
  "GHD Sit Up": ["abs", "hip flexors"],
  "Glute Bridge": ["glutes", "hamstrings"],
  "Glute Ham Raise": ["hamstrings", "glutes"],
  "Glute Kickback": ["glutes"],
  "Goblet Squat": ["quads", "glutes"],
  "Good Morning": ["hamstrings", "lower back"],
  "Groin Stretch Lunge": ["adductors", "glutes"],

  // H
  "Hack Squat": ["quads", "glutes"],
  "Hammer Curl": ["biceps"],
  "Hammer Strength Chest Press": ["chest", "triceps"],
  "Hammer Strength Row": ["lats", "traps"],
  "Hand Release Push Up": ["chest", "triceps"],
  "Handstand": ["shoulders", "core"],
  "Hack Squat Calf Raise": ["calves"],
  "Half Kneeling One Arm Lat Pulldown": ["lats"],
  "Half Squat": ["quads", "glutes"],
  "Hand Grippers": ["forearms"],
  "Hanging Windshield Wipers": ["core", "obliques"],
  "Heel Touch": ["obliques"],
  "Heel-Elevated Squat": ["quads"],
  "Hex Bar Deadlift": ["hamstrings", "glutes"],
  "Hex Bar Shrug": ["traps"],
  "High Plank": ["core", "shoulders"],
  "High Pulley Crunch": ["abs"],
  "High to Low Cable Fly": ["chest"],
  "Hip Extension": ["glutes", "hamstrings"],
  "Hip Thrust": ["glutes", "hamstrings"],
  "Handstand Push Up": ["shoulders", "triceps"],
  "Hang Clean": ["full body"],
  "Hang Power Clean": ["quads", "traps", "glutes"],
  "Hang Snatch": ["full body"],
  "Hanging Knee Raise": ["abs", "hip flexors"],
  "Hanging Leg Raise": ["abs", "hip flexors"],
  "High Pull Up": ["lats", "traps"],
  "Hip Abduction Machine": ["glute medius"],
  "Hip Adduction Machine": ["adductors"],
  "Horizontal Leg Press": ["quads", "glutes", "hamstrings"],

  // I
"Incline Bench Press": ["chest", "shoulders", "triceps"],
"Incline Dumbbell Curl": ["biceps"],
"Incline Push Up": ["chest", "shoulders", "triceps"],
"Incline Cable Curl": ["biceps"],
"Incline Dumbbell Fly": ["chest"],
"Incline Hammer Curl": ["biceps", "forearms"],
"Incline Machine Press": ["chest", "shoulders", "triceps"],
"Incline Side Lying Lateral Raise": ["shoulders"],
"Inverted Row": ["lats", "biceps", "rhomboids"],
"Iron Cross": ["shoulders", "chest"],

// J
"Jackknife Sit Up": ["core", "hip flexors"],
"Jammer Press": ["chest", "shoulders", "triceps"],
"Jefferson Curl": ["hamstrings", "glutes", "lower back"],
"Jefferson Deadlift": ["hamstrings", "glutes", "lower back"],
"Jefferson Squat": ["quads", "glutes"],
"Jerk": ["shoulders", "triceps", "quads", "glutes"],
"Jump Rope": ["cardio", "calves"],
"Jump Shrug": ["traps", "quads", "glutes"],
"Jump Squat": ["quads", "glutes", "hamstrings", "calves"],
"Jumping Jacks": ["cardio", "full body"],

// K
"Kettlebell Clean": ["quads", "glutes", "traps", "shoulders"],
"Kettlebell Deadlift": ["hamstrings", "glutes", "lower back"],
"Kettlebell Goblet Squat": ["quads", "glutes", "hamstrings"],
"Kettlebell Snatch": ["full body", "quads", "glutes", "shoulders"],
"Kettlebell Swing": ["hamstrings", "glutes", "lower back"],
"Kettlebell Thruster": ["quads", "glutes", "shoulders", "triceps"],
"Kettlebell Turkish Get Up": ["full body", "core", "shoulders"],
"Kipping Handstand Push Up": ["shoulders", "triceps"],
"Kipping Pull Up": ["lats", "biceps"],
"Knee Cobra Push Ups": ["chest", "triceps"],
"Knee Pike Push Ups": ["shoulders", "triceps"],
"Knee Push Ups": ["chest", "triceps", "shoulders"],
"Knee Raise": ["core", "hip flexors"],
"Knees to Elbows": ["core", "hip flexors"],
"Kneeling Finger Press": ["forearms"],
"Kneeling Fist to Palm": ["forearms"],
"Knuckle Push Ups": ["chest", "triceps", "forearms"],

// L
"L Pull Up": ["lats", "biceps", "core"],
"Landmine Press": ["shoulders", "chest", "triceps"],
"Landmine Row": ["lats", "traps", "rhomboids"],
"Lat Pulldown": ["lats", "biceps"],
"Lateral Box Jump": ["quads", "glutes", "hamstrings", "calves"],
"Lateral Lunge": ["quads", "glutes", "adductors"],
"Lawnmower Row": ["lats", "traps"],
"Leg Curl": ["hamstrings"],
"Leg Extension": ["quads"],
"Leg Press": ["quads", "glutes", "hamstrings"],
"Leg Press Calf Raise": ["calves"],
"Lying Leg Raises": ["core", "hip flexors"],
"Lunges": ["quads", "glutes", "hamstrings"],
"L Sit": ["core", "hip flexors"],
"Landmine Squat": ["quads", "glutes"],
"Larsen Press": ["chest", "triceps", "shoulders"],
"Low Plank": ["core"],
"Low to High Cable Fly": ["chest", "front delts"],
"Lying Cable Curl": ["biceps"],
"Lying Dumbbell Tricep Extension": ["triceps"],
"Lying Leg Curl": ["hamstrings"],
"Lying Tricep Extension (Skullcrushers)": ["triceps"],

// M
"Machine Bicep Curl": ["biceps"],
"Machine Chest Press": ["chest", "triceps", "shoulders"],
"Machine Fly": ["chest"],
"Machine Back Extension": ["lower back", "glutes"],
"Machine Calf Press": ["calves"],
"Machine Calf Raise": ["calves"],
"Machine Chest Fly": ["chest"],
"Machine Glute Kickback": ["glutes"],
"Machine High Row": ["lats", "traps", "rhomboids"],
"Machine Hip Thrust": ["glutes", "hamstrings"],
"Machine Lateral Raise": ["shoulders"],
"Machine Shoulder Press": ["shoulders", "triceps"],
"Machine Shrug": ["traps"],
"Machine Tricep Extension": ["triceps"],
"Machine Pullover": ["lats", "chest"],
"Machine Reverse Fly": ["rear delts", "traps", "rhomboids"],
"Machine Row": ["lats", "traps", "rhomboids"],
"Machine Seated Crunch": ["core"],
"Meadows Row": ["lats", "rear delts"],
"Military Press": ["shoulders", "triceps"],
"Muscle Snatch": ["traps", "shoulders", "quads", "glutes"],
"Medicine Ball Slam": ["core", "shoulders"],
"Mountain Climbers": ["core", "hip flexors", "cardio"],
"Muscle Up": ["lats", "chest", "triceps", "shoulders"],

// N
"Narrow Grip Bench Press": ["triceps", "chest"],
"Narrow Grip Push Up": ["triceps", "chest"],
"Neck Curl": ["neck flexors"],
"Neck Extension": ["neck extensors"],
"Neck Flexion": ["neck flexors"],
"Neck Lateral Flexion": ["neck"],
"Neck Rotation": ["neck"],
"Negative Chin Up": ["lats", "biceps"],
"Negative Pull Up": ["lats", "biceps"],
"Neutral Grip Lat Pulldown": ["lats", "biceps"],
"Neutral Grip Chin Up": ["lats", "biceps"],
"Neutral Grip Pull Up": ["lats", "biceps"],
"Nordic Curl": ["hamstrings"],
"No Equipment Air Bike": ["cardio", "core"],

// O
"One Arm Band Row": ["lats", "traps"],
"One Arm Barbell Row": ["lats", "traps"],
"One Arm Cable Curl": ["biceps"],
"One Arm Cable Extension": ["triceps"],
"One Arm Cable Fly": ["chest"],
"One Arm Seated Cable Row": ["lats", "rhomboids"],
"One Arm Chest Press": ["chest", "triceps", "shoulders"],
"One Arm Clean": ["quads", "glutes", "shoulders"],
"One Arm Deadlift": ["hamstrings", "glutes", "lower back"],
"One Arm Dumbbell Bench Press": ["chest", "triceps", "shoulders"],
"One Arm Dumbbell Curl": ["biceps"],
"One Arm Dumbbell Fly": ["chest"],
"One Arm Dumbbell Lateral Raise": ["shoulders"],
"One Arm Dumbbell Overhead Press": ["shoulders", "triceps"],
"One Arm Dumbbell Pullover": ["chest", "lats"],
"One Arm Dumbbell Row": ["lats", "traps", "rhomboids"],
"One Arm Dumbbell Shrug": ["traps"],
"One Arm Dumbbell Triceps Extension": ["triceps"],
"One Arm Floor Press": ["chest", "triceps"],
"One Arm Cable Front Raise": ["shoulders"],
"One Arm Dumbbell Preacher Curl": ["biceps"],
"One Arm Landmine Press": ["shoulders", "triceps"],
"One Arm Lat Pulldown": ["lats", "biceps"],
"One Arm Machine Reverse Fly": ["rear delts", "traps"],
"One Arm Pull Up": ["lats", "biceps"],
"One Arm Kettlebell Clean": ["quads", "glutes", "shoulders"],
"One Arm Kettlebell Deadlift": ["hamstrings", "glutes", "lower back"],
"One Arm Kettlebell Row": ["lats", "traps"],
"One Arm Push Up": ["chest", "triceps", "core"],
"One Arm Row (Machine)": ["lats", "rhomboids"],
"One Arm Smith Machine Row": ["lats", "traps"],
"One Arm Turkish Get Up": ["core", "shoulders", "glutes"],
"Open Chain Cable Row": ["lats", "rhomboids"],
"Overhead Cable Curl": ["biceps"],
"Overhead Dumbbell Press": ["shoulders", "triceps"],
"Overhead Lunge": ["quads", "glutes", "core"],
"Overhead Medicine Ball Slam": ["core", "shoulders"],
"Overhead Plate Carry": ["shoulders", "core"],
"Overhead Rope Extension": ["triceps"],
"Overhead Squat": ["quads", "glutes", "core", "shoulders"],
"Overhead Tricep Extension": ["triceps"],
"Overhead Walk": ["shoulders", "core"],
"Overhead Y Raise": ["rear delts", "shoulders"],

// P
"Pallof Press": ["core"],
"Pause Deadlift": ["hamstrings", "glutes", "lower back"],
"Pause Squat": ["quads", "glutes", "hamstrings"],
"Paused Bench Press": ["chest", "triceps", "shoulders"],
"Paused Incline Bench Press": ["chest", "triceps", "shoulders"],
"Pendulum Squat": ["quads", "glutes", "hamstrings"],
"Pilates": ["core"],
"Pin Squat": ["quads", "glutes", "hamstrings"],
"Pistol Squat": ["quads", "glutes", "hamstrings"],
"Planche": ["shoulders", "chest", "core"],
"Pec Deck Fly": ["chest"],
"Pendlay Row": ["lats", "traps", "rhomboids"],
"Physio Ball Crunch": ["core"],
"Pike Push Up": ["shoulders", "triceps"],
"Piriformis Stretch": ["stretch"],
"Plank": ["core"],
"Plank to Push Up": ["core", "chest", "triceps"],
"Plate Curl": ["biceps", "forearms"],
"Plate Front Raise": ["shoulders"],
"Plate Pinch Hold": ["forearms"],
"Power Clean": ["quads", "glutes", "traps", "shoulders"],
"Power Snatch": ["quads", "glutes", "traps", "shoulders"],
"Preacher Curl": ["biceps"],
"Prone Y Raise": ["rear delts", "traps"],
"Pull Over": ["chest", "lats"],
"Pull-Ups": ["lats", "biceps"],
"Push Jerk": ["shoulders", "triceps", "quads", "glutes"],
"Push Press": ["shoulders", "triceps", "quads", "glutes"],
"Push-Up": ["chest", "triceps", "shoulders"],
"Planche Push Up": ["shoulders", "chest", "core"],
"Plank Lean": ["core", "shoulders"],
"Preacher Hammer Curl": ["biceps", "forearms"],
"Press Around": ["chest", "shoulders"],
"Pseudo Planche Push Up": ["shoulders", "chest", "core"],

// Q
"Quad Extension": ["quads"],
"Quadruped Shoulder Tap": ["core", "shoulders"],

// R
"Rack Pull": ["hamstrings", "glutes", "lower back"],
"Rear Delt Fly": ["rear delts", "traps"],
"Renegade Row": ["lats", "core", "biceps"],
"Reverse Crunch": ["core"],
"Reverse Curl": ["biceps", "forearms"],
"Reverse Fly": ["rear delts", "traps"],
"Reverse Hyperextension": ["lower back", "glutes", "hamstrings"],
"Reverse Lunge": ["quads", "glutes", "hamstrings"],
"Ring Dip": ["chest", "triceps", "shoulders"],
"Ring Muscle Up": ["lats", "chest", "triceps", "shoulders"],
"Ring Push Up": ["chest", "triceps", "shoulders"],
"Rope Climb": ["full body", "lats", "biceps", "forearms"],
"Rope Face Pull": ["rear delts", "traps"],
"Rope Hammer Curl": ["biceps", "forearms"],
"Rowing Machine": ["cardio", "full body"],
"Russian Twist": ["core", "obliques"],
"Reverse EZ Bar Curl": ["biceps", "forearms"],
"Reverse Grip Bench Press": ["chest", "triceps", "shoulders"],
"Reverse Grip Bent Over Row": ["lats", "biceps"],
"Reverse Grip Lat Pulldown": ["lats", "biceps"],
"Reverse Grip Push Up": ["biceps", "chest"],
"Reverse Grip Tricep Pushdown": ["triceps"],
"Reverse Nordic Curl": ["quads"],
"Reverse Plank": ["core", "glutes", "shoulders"],
"Reverse Wrist Curl": ["forearms"],
"Roman Chair Side Bend": ["obliques"],
"Romanian Deadlift": ["glutes", "hamstrings"],

// S
"Scissor Kick": ["core"],
"Seated Calf Raise": ["calves"],
"Seated Cable Row": ["lats", "traps", "rhomboids"],
"Seated Leg Curl": ["hamstrings"],
"Seated Overhead Press": ["shoulders", "triceps"],
"Seated Row": ["lats", "traps"],
"Shoulder Press": ["shoulders"],
"Side Lateral Raise": ["shoulders"],
"Side Plank": ["core", "obliques"],
"Single Arm Cable Row": ["lats", "rhomboids"],
"Single Arm Dumbbell Press": ["shoulders", "triceps"],
"Single Arm Row": ["lats", "traps"],
"Single Leg Deadlift": ["hamstrings", "glutes"],
"Single Leg Glute Bridge": ["glutes", "hamstrings"],
"Single Leg Press": ["quads", "glutes"],
"Sit Up": ["core"],
"Skater Squat": ["quads", "glutes"],
"Skullcrusher": ["triceps"],
"Sled Push": ["quads", "glutes", "hamstrings", "calves"],
"Side Crunch": ["obliques"],
"Side Leg Raise": ["hip abductors", "glutes"],
"Side Lunge": ["quads", "glutes", "adductors"],
"Side Lying Hip Adduction": ["adductors"],
"Single Arm Hammer Curl": ["biceps", "forearms"],
"Single Arm Tricep Pushdown": ["triceps"],
"Single Leg Dumbbell Deadlift": ["hamstrings", "glutes"],
"Single Leg Extension": ["quads"],
"Single Leg Lying Leg Curl": ["hamstrings"],
"Single Leg Romanian Deadlift": ["hamstrings", "glutes"],
"Single Leg Seated Calf Raise": ["calves"],
"Single Leg Squat": ["quads", "glutes", "hamstrings"],
"Sissy Squat": ["quads"],
"Smith Machine Bench Press": ["chest", "triceps", "shoulders"],
"Smith Machine Bent Over Row": ["lats", "traps"],
"Smith Machine Bulgarian Split Squat": ["quads", "glutes", "hamstrings"],
"Smith Machine Calf Raise": ["calves"],
"Smith Machine Incline Bench Press": ["chest", "shoulders", "triceps"],
"Smith Machine Reverse Grip Bent Over Row": ["lats", "biceps"],
"Smith Machine Shoulder Press": ["shoulders", "triceps"],
"Smith Machine Shrug": ["traps"],
"Smith Machine Sissy Squat": ["quads"],
"Smith Machine Squat": ["quads", "glutes", "hamstrings"],
"Snatch Pull": ["traps", "quads", "glutes", "hamstrings"],
"Snatch": ["full body", "quads", "glutes", "shoulders"],
"Snatch Grip Deadlift": ["hamstrings", "glutes", "traps"],
"Snow Angel": ["shoulders", "rear delts"],
"Split Squat": ["quads", "glutes", "hamstrings"],
"Split Squat Jump": ["quads", "glutes", "calves"],
"Spider Curl": ["biceps"],
"Split Jerk": ["quads", "glutes", "shoulders", "triceps"],
"Spoto Press": ["chest", "triceps", "shoulders"],
"Standing Cable Crunch": ["core"],
"Standing Machine Lateral Raise": ["shoulders"],
"Squat": ["quads", "glutes", "hamstrings"],
"Squat Jump": ["quads", "glutes", "hamstrings", "calves"],
"Stair Climber": ["cardio", "quads", "glutes"],
"Standing Calf Raise": ["calves"],
"Standing Cable Row": ["lats", "rhomboids"],
"Standing Leg Curl": ["hamstrings"],
"Standing Leg Raise": ["hip flexors", "core"],
"Step Up": ["quads", "glutes"],
"Step Up with Knee Raise": ["quads", "glutes", "core"],
"Stiff Leg Deadlift": ["hamstrings", "glutes"],
"Straight Arm Pulldown": ["lats"],
"Strict Curl": ["biceps"],
"Strict Press": ["shoulders", "triceps"],
"Sumo Deadlift": ["glutes", "hamstrings", "adductors"],
"Sumo Squat": ["glutes", "quads", "adductors"],
"Superman": ["lower back", "glutes"],
"Safety Bar Squat": ["quads", "glutes", "hamstrings"],
"Seated Dip Machine": ["triceps"],
"Seated Dumbbell Curl": ["biceps"],
"Seated Dumbbell Shoulder Press": ["shoulders", "triceps"],
"Seated Dumbbell Tricep Extension": ["triceps"],
"Seated Hammer Curl": ["biceps", "forearms"],
"Seated Shoulder Press": ["shoulders", "triceps"],
"Seated Smith Machine Shoulder Press": ["shoulders", "triceps"],
"Shoulder Pin Press": ["shoulders", "triceps"],

// T
"Table Inverted Row": ["lats", "biceps", "rhomboids"],
"Tate Press": ["triceps"],
"Tiger Bend Push Ups": ["triceps", "shoulders"],
"Toes to Bar": ["core", "hip flexors"],
"Torso Rotation Machine": ["obliques"],
"T Bar Row": ["lats", "traps", "rhomboids"],
"Towel Pull Up": ["lats", "biceps", "forearms"],
"Tricep Dips": ["triceps", "chest", "shoulders"],
"Tricep Extension": ["triceps"],
"Tricep Kickback": ["triceps"],
"Tricep Pushdown": ["triceps"],
"Tricep Rope Pushdown": ["triceps"],
"Trap Bar Deadlift": ["quads", "glutes", "hamstrings"],
"Tree Pose": ["balance", "core"],
"Turkish Get Up": ["full body", "core", "shoulders"],

// U
"Upright Row": ["traps", "shoulders"],
"Upright Shoulder Raise": ["traps"],
"Uttanasana (Forward Bend)": ["hamstrings", "lower back"],

// V
"V Squat": ["quads", "glutes", "hamstrings"],
"V Ups": ["core"],
"Vertical Leg Press": ["quads", "glutes", "hamstrings"],
"Vertical Traction Machine": ["lats", "biceps"],
"Viking Press": ["shoulders", "triceps"],
"V Sit": ["core"],
"Vertical Jump": ["quads", "glutes", "calves"],
"Volleyball Serve": ["shoulders"],

// W
"Wall Ball Shot": ["quads", "glutes", "shoulders", "core"],
"Wall Sit": ["quads", "glutes"],
"Walking Lunge": ["quads", "glutes", "hamstrings"],
"Water Rowing": ["cardio", "full body"],
"Wide Grip Lat Pulldown": ["lats", "biceps"],
"Waiter Curl": ["biceps", "forearms"],
"Wall Push Up": ["chest", "triceps"],
"Wide Grip Bench Press": ["chest", "triceps", "shoulders"],
"Wide Grip Chest Press": ["chest", "triceps"],
"Wide Grip Push Up": ["chest", "shoulders", "triceps"],
"Wide Grip Seated Cable Row": ["lats", "rear delts"],
"Wide Grip Pull Up": ["lats", "biceps"],
"Windmill": ["core", "obliques"],
"Wrist Curl": ["forearms"],

// X
"X Band Walk": ["glutes", "hip abductors"],

// Y
"Y Raise": ["rear delts", "traps"],
"Yoke Walk": ["full body", "traps", "core"],
"Yates Row": ["lats", "traps", "biceps"],

// Z
"Z Press": ["shoulders", "triceps", "core"],
"Zercher Deadlift": ["hamstrings", "glutes", "lower back", "core"],
"Zottman Curl": ["biceps", "forearms"],
"Zercher Squat": ["quads", "glutes", "core"],
};