import { PROGRESSION } from "./progression";

export const EXERCISE_PROGRESSION = {

  // --- A ---
  "Ab Wheel Rollout": PROGRESSION.BODYWEIGHT_ONLY,
  "Abcoaster": PROGRESSION.BODYWEIGHT_ONLY,
  "Air Bike": PROGRESSION.BODYWEIGHT_ONLY,
  "Archer Pull Ups": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Archer Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Arnold Press": PROGRESSION.DEFAULT,
  "Assisted Chin Ups": PROGRESSION.ASSISTANCE_BASED,
  "Assisted Dips": PROGRESSION.ASSISTANCE_BASED,
  "Assisted Muscle Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Assisted Pull Ups": PROGRESSION.ASSISTANCE_BASED,

  // --- B ---
  "Back Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "Back Lever": PROGRESSION.BODYWEIGHT_ONLY,
  "Balance Board Squat": PROGRESSION.BODYWEIGHT_ONLY,
  "Barbell Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Barbell Clean": PROGRESSION.DEFAULT,
  "Barbell Concentration Curl": PROGRESSION.HIGH_REP,
  "Barbell Curl": PROGRESSION.HIGH_REP,
  "Barbell Flexion Row": PROGRESSION.DEFAULT,
  "Barbell Front Raise": PROGRESSION.DEFAULT,
  "Barbell Glute Bridge": PROGRESSION.DEFAULT,
  "Barbell Hack Squat": PROGRESSION.HEAVY_MACHINE,
  "Barbell Lunge": PROGRESSION.HIGH_REP,
  "Barbell Overhead Press": PROGRESSION.DEFAULT,
  "Barbell Power Shrug": PROGRESSION.HEAVY_MACHINE,
  "Barbell Pullover": PROGRESSION.DEFAULT,
  "Barbell Reverse Curl": PROGRESSION.HIGH_REP,
  "Barbell Reverse Lunge": PROGRESSION.HIGH_REP,
  "Barbell Row": PROGRESSION.DEFAULT,
  "Barbell Shrug": PROGRESSION.HEAVY_MACHINE,
  "Barbell Step Up": PROGRESSION.HIGH_REP,
  "Barbell Thruster": PROGRESSION.DEFAULT,
  "Barbell Upright Row": PROGRESSION.DEFAULT,
  "Barbell Z Press": PROGRESSION.DEFAULT,
  "Bayesian Curl": PROGRESSION.HIGH_REP,
  "Behind the Back Deadlift": PROGRESSION.DEFAULT,
  "Behind the Back Neck Press": PROGRESSION.DEFAULT,
  "Behind the Back Barbell Shrug": PROGRESSION.HEAVY_MACHINE,
  "Behind the Neck Press": PROGRESSION.DEFAULT,
  "Bench Dips": PROGRESSION.BODYWEIGHT_ONLY,
  "Bench Pin Press": PROGRESSION.DEFAULT,
  "Bench Press": PROGRESSION.DEFAULT,
  "Bench Pull": PROGRESSION.DEFAULT,
  "Bent Arm Barbell Pullover": PROGRESSION.DEFAULT,
  "Bent Over Dumbbell Row": PROGRESSION.DEFAULT,
  "Bent Over Row": PROGRESSION.DEFAULT,
  "Bicycle Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Bicep Curl": PROGRESSION.DEFAULT,
  "Bird Dog": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Squat": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Calf Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Concentration Curl": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Good Morning": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Kneeling Tricep Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Lateral Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Military Press": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Overhead Tricep Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "Bodyweight Tricep Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "Box Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Box Squat": PROGRESSION.HEAVY_MACHINE,
  "Broad Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Bulgarian Split Squat": PROGRESSION.HIGH_REP,
  "Burpees": PROGRESSION.BODYWEIGHT_ONLY,

  // --- C ---
  "Cable Bent Over Row": PROGRESSION.DEFAULT,
  "Cable Bicep Curl": PROGRESSION.HIGH_REP,
  "Cable Chest Fly": PROGRESSION.HIGH_REP,
  "Cable Chest Press": PROGRESSION.DEFAULT,
  "Cable Crossover": PROGRESSION.HIGH_REP,
  "Cable Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Cable External Rotation": PROGRESSION.BODYWEIGHT_ONLY,
  "Cable Face Pull": PROGRESSION.HIGH_REP,
  "Cable Front Raise": PROGRESSION.HIGH_REP,
  "Cable Hammer Curl": PROGRESSION.HIGH_REP,
  "Cable Internal Rotation": PROGRESSION.BODYWEIGHT_ONLY,
  "Cable Kickback": PROGRESSION.HIGH_REP,
  "Cable Lateral Raise": PROGRESSION.HIGH_REP,
  "Cable Leg Curl": PROGRESSION.HEAVY_MACHINE,
  "Cable Leg Extension": PROGRESSION.HEAVY_MACHINE,
  "Cable Overhead Tricep Extension": PROGRESSION.HIGH_REP,
  "Cable Pull Through": PROGRESSION.DEFAULT,
  "Cable Rear Delt Fly": PROGRESSION.HIGH_REP,
  "Cable Reverse Curl": PROGRESSION.HIGH_REP,
  "Cable Reverse Fly": PROGRESSION.HIGH_REP,
  "Cable Reverse Wrist Curl": PROGRESSION.HIGH_REP,
  "Cable Rope Overhead Extension": PROGRESSION.HIGH_REP,
  "Cable Shrug": PROGRESSION.HEAVY_MACHINE,
  "Cable Tricep Kickback": PROGRESSION.HIGH_REP,
  "Cable Upright Row": PROGRESSION.DEFAULT,
  "Cable Woodchopper": PROGRESSION.BODYWEIGHT_ONLY,
  "Cable Wrist Curl": PROGRESSION.HIGH_REP,
  "Cable Y Raise": PROGRESSION.HIGH_REP,
  "Calf Raises": PROGRESSION.HEAVY_MACHINE,
  "Captain's Chair Knee Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Captain's Chair Leg Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Cheat Curl": PROGRESSION.HIGH_REP,
  "Chest Dip": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Chest Press": PROGRESSION.DEFAULT,
  "Chest Press Machine": PROGRESSION.HEAVY_MACHINE,
  "Chest Supported Dumbbell Row": PROGRESSION.DEFAULT,
  "Chest Supported Dumbbell Shrug": PROGRESSION.HEAVY_MACHINE,
  "Chest Supported T Bar Row": PROGRESSION.HEAVY_MACHINE,
  "Chin Ups": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Clamshells": PROGRESSION.BODYWEIGHT_ONLY,
  "Clap Pull Ups": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Clap Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Clean": PROGRESSION.DEFAULT,
  "Clean and Jerk": PROGRESSION.DEFAULT,
  "Clean and Press": PROGRESSION.DEFAULT,
  "Clean High Pull": PROGRESSION.DEFAULT,
  "Clean Pull": PROGRESSION.DEFAULT,
  "Close Grip Bench Press": PROGRESSION.DEFAULT,
  "Close Grip Dumbbell Bench Press": PROGRESSION.DEFAULT,
  "Close Grip Incline Bench Press": PROGRESSION.DEFAULT,
  "Close Grip Lat Pulldown": PROGRESSION.DEFAULT,
  "Close Grip Pull Ups": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Close Grip Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Crossover Lunge": PROGRESSION.HIGH_REP,
  "Cross Body Cable Tricep Extension": PROGRESSION.HIGH_REP,
  "Cross Body Hammer Curl": PROGRESSION.HIGH_REP,
  "Cross Body Lat Pull Around": PROGRESSION.DEFAULT,
  "Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Crunch Machine": PROGRESSION.HEAVY_MACHINE,
  "Cycling": PROGRESSION.TIME_BASED,

  // --- D ---
  "Dead Bug": PROGRESSION.BODYWEIGHT_ONLY,
  "Dead Hang": PROGRESSION.TIME_BASED,
  "Deadlift": PROGRESSION.HEAVY_MACHINE,
  "Decline Bench Press": PROGRESSION.DEFAULT,
  "Decline Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Decline Dumbbell Press": PROGRESSION.DEFAULT,
  "Deficit Deadlift": PROGRESSION.DEFAULT,
  "Decline Dumbbell Fly": PROGRESSION.HIGH_REP,
  "Decline Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Decline Pike Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Decline Sit-Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Deficit Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Diamond Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Double Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Dragon Flag": PROGRESSION.BODYWEIGHT_ONLY,
  "Dumbbell Bench Pull": PROGRESSION.DEFAULT,
  "Dumbbell Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Dumbbell Clean and Press": PROGRESSION.DEFAULT,
  "Dumbbell External Rotation": PROGRESSION.BODYWEIGHT_ONLY,
  "Dumbbell Face Pull": PROGRESSION.HIGH_REP,
  "Dumbbell Floor Press": PROGRESSION.DEFAULT,
  "Dumbbell Front Squat": PROGRESSION.DEFAULT,
  "Dumbbell Hang Clean": PROGRESSION.DEFAULT,
  "Dumbbell High Pull": PROGRESSION.DEFAULT,
  "Dumbbell Incline Y Raise": PROGRESSION.HIGH_REP,
  "Dumbbell Larsen Press": PROGRESSION.DEFAULT,
  "Dumbbell Push Press": PROGRESSION.DEFAULT,
  "Dumbbell Reverse Curl": PROGRESSION.HIGH_REP,
  "Dumbbell Reverse Fly": PROGRESSION.HIGH_REP,
  "Dumbbell Reverse Wrist Curl": PROGRESSION.HIGH_REP,
  "Dumbbell Side Bend": PROGRESSION.BODYWEIGHT_ONLY,
  "Dumbbell Snatch": PROGRESSION.DEFAULT,
  "Dumbbell Spider Curl": PROGRESSION.HIGH_REP,
  "Dumbbell Squat": PROGRESSION.DEFAULT,
  "Dumbbell Tricep Kickback": PROGRESSION.HIGH_REP,
  "Dumbbell Upright Row": PROGRESSION.DEFAULT,
  "Dumbbell Walking Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Dumbbell Wrist Curl": PROGRESSION.HIGH_REP,
  "Dumbbell Bench Press": PROGRESSION.DEFAULT,
  "Dumbbell Bulgarian Split Squat": PROGRESSION.HIGH_REP,
  "Dumbbell Clean": PROGRESSION.DEFAULT,
  "Dumbbell Concentration Curl": PROGRESSION.HIGH_REP,
  "Dumbbell Bicep Curl": PROGRESSION.HIGH_REP,
  "Dumbbell Deadlift": PROGRESSION.DEFAULT,
  "Dumbbell Flyes": PROGRESSION.HIGH_REP,
  "Dumbbell Front Raise": PROGRESSION.HIGH_REP,
  "Dumbbell Hammer Curl": PROGRESSION.HIGH_REP,
  "Incline Dumbbell Bench Press": PROGRESSION.DEFAULT,
  "Dumbbell Lateral Raise": PROGRESSION.HIGH_REP,
  "Dumbbell Lunge": PROGRESSION.HIGH_REP,
  "Dumbbell Overhead Press": PROGRESSION.DEFAULT,
  "Dumbbell Pullover": PROGRESSION.DEFAULT,
  "Dumbbell Romanian Deadlift": PROGRESSION.DEFAULT,
  "Dumbbell Row": PROGRESSION.DEFAULT,
  "Dumbbell Shoulder Press": PROGRESSION.DEFAULT,
  "Dumbbell Shrug": PROGRESSION.HEAVY_MACHINE,
  "Dumbbell Skullcrusher": PROGRESSION.HIGH_REP,
  "Dumbbell Split Squat": PROGRESSION.HIGH_REP,
  "Dumbbell Step Up": PROGRESSION.HIGH_REP,
  "Dumbbell Thruster": PROGRESSION.DEFAULT,
  "Dumbbell Tricep Extension": PROGRESSION.HIGH_REP,
  "Dumbbell Z Press": PROGRESSION.DEFAULT,
  "Depth Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Dip Machine": PROGRESSION.HEAVY_MACHINE,
  "Dips": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Donkey Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Double Under": PROGRESSION.BODYWEIGHT_ONLY,
  "Drag Curl": PROGRESSION.HIGH_REP,

  // --- E ---
  "Elbow to Knee Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Elliptical Trainer": PROGRESSION.TIME_BASED,
  "Elevated Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Explosive Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Explosive Squat Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "EZ Bar Lying Triceps Extension": PROGRESSION.HIGH_REP,
  "EZ Bar Preacher Curl": PROGRESSION.HIGH_REP,
  "EZ Bar Spider Curl": PROGRESSION.HIGH_REP,
  "EZ Bar Curl": PROGRESSION.HIGH_REP,
  "EZ Bar Skullcrusher": PROGRESSION.HIGH_REP,
  "EZ Bar Upright Row": PROGRESSION.DEFAULT,
  "External Shoulder Rotation": PROGRESSION.BODYWEIGHT_ONLY,

  // --- F ---
  "Face Pull": PROGRESSION.HIGH_REP,
  "Feet Elevated Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Fingertip Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Fire Hydrant": PROGRESSION.BODYWEIGHT_ONLY,
  "Floor Press": PROGRESSION.DEFAULT,
  "Farmer's Walk": PROGRESSION.TIME_BASED,
  "Floor Hip Abduction": PROGRESSION.BODYWEIGHT_ONLY,
  "Floor Hip Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "Floor T Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Flutter Kick": PROGRESSION.BODYWEIGHT_ONLY,
  "Forward Lunge": PROGRESSION.HIGH_REP,
  "Front Lever": PROGRESSION.BODYWEIGHT_ONLY,
  "Front Raise": PROGRESSION.HIGH_REP,
  "Front Squat": PROGRESSION.HEAVY_MACHINE,

  // --- G ---
  "GHD Back Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "GHD Sit Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Glute Bridge": PROGRESSION.BODYWEIGHT_ONLY,
  "Glute Ham Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Glute Kickback": PROGRESSION.BODYWEIGHT_ONLY,
  "Goblet Squat": PROGRESSION.HIGH_REP,
  "Good Morning": PROGRESSION.DEFAULT,
  "Groin Stretch Lunge": PROGRESSION.HIGH_REP,

  // --- H ---
  "Hack Squat": PROGRESSION.HEAVY_MACHINE,
  "Hammer Curl": PROGRESSION.HIGH_REP,
  "Hammer Strength Chest Press": PROGRESSION.HEAVY_MACHINE,
  "Hammer Strength Row": PROGRESSION.HEAVY_MACHINE,
  "Hand Release Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Handstand": PROGRESSION.BODYWEIGHT_ONLY,
  "Hack Squat Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Half Kneeling One Arm Lat Pulldown": PROGRESSION.DEFAULT,
  "Half Squat": PROGRESSION.HEAVY_MACHINE,
  "Hand Grippers": PROGRESSION.BODYWEIGHT_ONLY,
  "Hanging Windshield Wipers": PROGRESSION.BODYWEIGHT_ONLY,
  "Heel Touch": PROGRESSION.BODYWEIGHT_ONLY,
  "Heel-Elevated Squat": PROGRESSION.DEFAULT,
  "Hex Bar Deadlift": PROGRESSION.DEFAULT,
  "Hex Bar Shrug": PROGRESSION.HEAVY_MACHINE,
  "High Plank": PROGRESSION.TIME_BASED,
  "High Pulley Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "High to Low Cable Fly": PROGRESSION.HIGH_REP,
  "Hip Extension": PROGRESSION.DEFAULT,
  "Hip Thrust": PROGRESSION.DEFAULT,
  "Handstand Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Hang Clean": PROGRESSION.DEFAULT,
  "Hang Power Clean": PROGRESSION.DEFAULT,
  "Hang Snatch": PROGRESSION.DEFAULT,
  "Hanging Knee Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Hanging Leg Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "High Pull Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Hip Abduction Machine": PROGRESSION.HEAVY_MACHINE,
  "Hip Adduction Machine": PROGRESSION.HEAVY_MACHINE,
  "Horizontal Leg Press": PROGRESSION.HEAVY_MACHINE,

  // --- I ---
  "Incline Bench Press": PROGRESSION.DEFAULT,
  "Incline Dumbbell Curl": PROGRESSION.HIGH_REP,
  "Incline Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Incline Cable Curl": PROGRESSION.HIGH_REP,
  "Incline Dumbbell Fly": PROGRESSION.HIGH_REP,
  "Incline Hammer Curl": PROGRESSION.HIGH_REP,
  "Incline Machine Press": PROGRESSION.HEAVY_MACHINE,
  "Incline Side Lying Lateral Raise": PROGRESSION.HIGH_REP,
  "Inverted Row": PROGRESSION.BODYWEIGHT_ONLY,
  "Iron Cross": PROGRESSION.BODYWEIGHT_ONLY,

  // --- J ---
  "Jackknife Sit Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Jammer Press": PROGRESSION.HEAVY_MACHINE,
  "Jefferson Curl": PROGRESSION.DEFAULT,
  "Jefferson Deadlift": PROGRESSION.DEFAULT,
  "Jefferson Squat": PROGRESSION.DEFAULT,
  "Jerk": PROGRESSION.DEFAULT,
  "Jump Rope": PROGRESSION.TIME_BASED,
  "Jump Shrug": PROGRESSION.DEFAULT,
  "Jump Squat": PROGRESSION.BODYWEIGHT_ONLY,
  "Jumping Jacks": PROGRESSION.BODYWEIGHT_ONLY,

  // --- K ---
  "Kettlebell Clean": PROGRESSION.DEFAULT,
  "Kettlebell Deadlift": PROGRESSION.DEFAULT,
  "Kettlebell Goblet Squat": PROGRESSION.HIGH_REP,
  "Kettlebell Snatch": PROGRESSION.DEFAULT,
  "Kettlebell Swing": PROGRESSION.DEFAULT,
  "Kettlebell Thruster": PROGRESSION.DEFAULT,
  "Kettlebell Turkish Get Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Kipping Handstand Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Kipping Pull Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Knee Cobra Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Knee Pike Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Knee Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Knee Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Knees to Elbows": PROGRESSION.BODYWEIGHT_ONLY,
  "Kneeling Finger Press": PROGRESSION.BODYWEIGHT_ONLY,
  "Kneeling Fist to Palm": PROGRESSION.BODYWEIGHT_ONLY,
  "Knuckle Push Ups": PROGRESSION.BODYWEIGHT_ONLY,

  // --- L ---
  "L Pull Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Landmine Press": PROGRESSION.DEFAULT,
  "Landmine Row": PROGRESSION.DEFAULT,
  "Lat Pulldown": PROGRESSION.DEFAULT,
  "Lateral Box Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Lateral Lunge": PROGRESSION.HIGH_REP,
  "Lawnmower Row": PROGRESSION.DEFAULT,
  "Leg Curl": PROGRESSION.HEAVY_MACHINE,
  "Leg Extension": PROGRESSION.HEAVY_MACHINE,
  "Leg Press": PROGRESSION.HEAVY_MACHINE,
  "Leg Press Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Lying Leg Raises": PROGRESSION.BODYWEIGHT_ONLY,
  "Lunges": PROGRESSION.HIGH_REP,
  "L Sit": PROGRESSION.BODYWEIGHT_ONLY,
  "Landmine Squat": PROGRESSION.DEFAULT,
  "Larsen Press": PROGRESSION.DEFAULT,
  "Low Plank": PROGRESSION.TIME_BASED,
  "Low to High Cable Fly": PROGRESSION.HIGH_REP,
  "Lying Cable Curl": PROGRESSION.HIGH_REP,
  "Lying Dumbbell Tricep Extension": PROGRESSION.HIGH_REP,
  "Lying Leg Curl": PROGRESSION.HEAVY_MACHINE,
  "Lying Tricep Extension (Skull Crushers)": PROGRESSION.HIGH_REP,

  // --- M ---
  "Machine Bicep Curl": PROGRESSION.HIGH_REP,
  "Machine Chest Press": PROGRESSION.HEAVY_MACHINE,
  "Machine Fly": PROGRESSION.HIGH_REP,
  "Machine Back Extension": PROGRESSION.HEAVY_MACHINE,
  "Machine Calf Press": PROGRESSION.HEAVY_MACHINE,
  "Machine Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Machine Chest Fly": PROGRESSION.HIGH_REP,
  "Machine Glute Kickback": PROGRESSION.HEAVY_MACHINE,
  "Machine High Row": PROGRESSION.HEAVY_MACHINE,
  "Machine Hip Thrust": PROGRESSION.HEAVY_MACHINE,
  "Machine Lateral Raise": PROGRESSION.HIGH_REP,
  "Machine Shoulder Press": PROGRESSION.HEAVY_MACHINE,
  "Machine Shrug": PROGRESSION.HEAVY_MACHINE,
  "Machine Tricep Extension": PROGRESSION.HIGH_REP,
  "Machine Pullover": PROGRESSION.HEAVY_MACHINE,
  "Machine Reverse Fly": PROGRESSION.HIGH_REP,
  "Machine Row": PROGRESSION.HEAVY_MACHINE,
  "Machine Seated Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Meadows Row": PROGRESSION.DEFAULT,
  "Military Press": PROGRESSION.DEFAULT,
  "Muscle Snatch": PROGRESSION.DEFAULT,
  "Medicine Ball Slam": PROGRESSION.BODYWEIGHT_ONLY,
  "Mountain Climbers": PROGRESSION.BODYWEIGHT_ONLY,
  "Muscle Up": PROGRESSION.BODYWEIGHT_LOADABLE,

  // --- N ---
  "Narrow Grip Bench Press": PROGRESSION.DEFAULT,
  "Narrow Grip Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Neck Curl": PROGRESSION.BODYWEIGHT_ONLY,
  "Neck Extension": PROGRESSION.BODYWEIGHT_ONLY,
  "Neck Flexion": PROGRESSION.BODYWEIGHT_ONLY,
  "Neck Lateral Flexion": PROGRESSION.BODYWEIGHT_ONLY,
  "Neck Rotation": PROGRESSION.BODYWEIGHT_ONLY,
  "Negative Chin Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Negative Pull Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Neutral Grip Lat Pulldown": PROGRESSION.DEFAULT,
  "Neutral Grip Chin Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Neutral Grip Pull Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Nordic Curl": PROGRESSION.BODYWEIGHT_ONLY,
  "No Equipment Air Bike": PROGRESSION.BODYWEIGHT_ONLY,

  // --- O ---
  "One Arm Band Row": PROGRESSION.BODYWEIGHT_ONLY,
  "One Arm Barbell Row": PROGRESSION.DEFAULT,
  "One Arm Cable Curl": PROGRESSION.HIGH_REP,
  "One Arm Cable Extension": PROGRESSION.HIGH_REP,
  "One Arm Cable Fly": PROGRESSION.HIGH_REP,
  "One Arm Seated Cable Row": PROGRESSION.DEFAULT,
  "One Arm Chest Press": PROGRESSION.DEFAULT,
  "One Arm Clean": PROGRESSION.DEFAULT,
  "One Arm Deadlift": PROGRESSION.DEFAULT,
  "One Arm Dumbbell Bench Press": PROGRESSION.DEFAULT,
  "One Arm Dumbbell Curl": PROGRESSION.HIGH_REP,
  "One Arm Dumbbell Fly": PROGRESSION.HIGH_REP,
  "One Arm Dumbbell Lateral Raise": PROGRESSION.HIGH_REP,
  "One Arm Dumbbell Overhead Press": PROGRESSION.DEFAULT,
  "One Arm Dumbbell Pullover": PROGRESSION.DEFAULT,
  "One Arm Dumbbell Row": PROGRESSION.DEFAULT,
  "One Arm Dumbbell Shrug": PROGRESSION.HEAVY_MACHINE,
  "One Arm Dumbbell Triceps Extension": PROGRESSION.HIGH_REP,
  "One Arm Floor Press": PROGRESSION.DEFAULT,
  "One Arm Cable Front Raise": PROGRESSION.HIGH_REP,
  "One Arm Dumbbell Preacher Curl": PROGRESSION.HIGH_REP,
  "One Arm Landmine Press": PROGRESSION.DEFAULT,
  "One Arm Lat Pulldown": PROGRESSION.DEFAULT,
  "One Arm Machine Reverse Fly": PROGRESSION.HIGH_REP,
  "One Arm Pull Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "One Arm Kettlebell Clean": PROGRESSION.DEFAULT,
  "One Arm Kettlebell Deadlift": PROGRESSION.DEFAULT,
  "One Arm Kettlebell Row": PROGRESSION.DEFAULT,
  "One Arm Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "One Arm Row (Machine)": PROGRESSION.HEAVY_MACHINE,
  "One Arm Smith Machine Row": PROGRESSION.HEAVY_MACHINE,
  "One Arm Turkish Get Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Open Chain Cable Row": PROGRESSION.DEFAULT,
  "Overhead Cable Curl": PROGRESSION.HIGH_REP,
  "Overhead Dumbbell Press": PROGRESSION.DEFAULT,
  "Overhead Lunge": PROGRESSION.DEFAULT,
  "Overhead Medicine Ball Slam": PROGRESSION.BODYWEIGHT_ONLY,
  "Overhead Plate Carry": PROGRESSION.TIME_BASED,
  "Overhead Rope Extension": PROGRESSION.HIGH_REP,
  "Overhead Squat": PROGRESSION.DEFAULT,
  "Overhead Tricep Extension": PROGRESSION.HIGH_REP,
  "Overhead Walk": PROGRESSION.TIME_BASED,
  "Overhead Y Raise": PROGRESSION.HIGH_REP,

  // --- P ---
  "Pallof Press": PROGRESSION.BODYWEIGHT_ONLY,
  "Pause Deadlift": PROGRESSION.DEFAULT,
  "Pause Squat": PROGRESSION.DEFAULT,
  "Paused Bench Press": PROGRESSION.DEFAULT,
  "Paused Incline Bench Press": PROGRESSION.DEFAULT,
  "Pendulum Squat": PROGRESSION.HEAVY_MACHINE,
  "Pilates": PROGRESSION.BODYWEIGHT_ONLY,
  "Pin Squat": PROGRESSION.DEFAULT,
  "Pistol Squat": PROGRESSION.BODYWEIGHT_ONLY,
  "Planche": PROGRESSION.BODYWEIGHT_ONLY,
  "Pec Deck Fly": PROGRESSION.HIGH_REP,
  "Pendlay Row": PROGRESSION.DEFAULT,
  "Physio Ball Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Pike Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Piriformis Stretch": PROGRESSION.BODYWEIGHT_ONLY,
  "Plank": PROGRESSION.TIME_BASED,
  "Plank to Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Plate Curl": PROGRESSION.HIGH_REP,
  "Plate Front Raise": PROGRESSION.HIGH_REP,
  "Plate Pinch Hold": PROGRESSION.BODYWEIGHT_ONLY,
  "Power Clean": PROGRESSION.DEFAULT,
  "Power Snatch": PROGRESSION.DEFAULT,
  "Preacher Curl": PROGRESSION.HIGH_REP,
  "Prone Y Raise": PROGRESSION.HIGH_REP,
  "Pull Over": PROGRESSION.DEFAULT,
  "Pull-Ups": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Push Jerk": PROGRESSION.DEFAULT,
  "Push Press": PROGRESSION.DEFAULT,
  "Push-Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Planche Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Plank Lean": PROGRESSION.BODYWEIGHT_ONLY,
  "Preacher Hammer Curl": PROGRESSION.HIGH_REP,
  "Press Around": PROGRESSION.DEFAULT,
  "Pseudo Planche Push Up": PROGRESSION.BODYWEIGHT_ONLY,

  // --- Q ---
  "Quad Extension": PROGRESSION.HEAVY_MACHINE,
  "Quadruped Shoulder Tap": PROGRESSION.BODYWEIGHT_ONLY,

  // --- R ---
  "Rack Pull": PROGRESSION.DEFAULT,
  "Rear Delt Fly": PROGRESSION.HIGH_REP,
  "Renegade Row": PROGRESSION.DEFAULT,
  "Reverse Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Reverse Curl": PROGRESSION.HIGH_REP,
  "Reverse Fly": PROGRESSION.HIGH_REP,
  "Reverse Hyperextension": PROGRESSION.DEFAULT,
  "Reverse Lunge": PROGRESSION.HIGH_REP,
  "Ring Dip": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Ring Muscle Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Ring Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Rope Climb": PROGRESSION.BODYWEIGHT_ONLY,
  "Rope Face Pull": PROGRESSION.HIGH_REP,
  "Rope Hammer Curl": PROGRESSION.HIGH_REP,
  "Rowing Machine": PROGRESSION.TIME_BASED,
  "Russian Twist": PROGRESSION.BODYWEIGHT_ONLY,
  "Reverse EZ Bar Curl": PROGRESSION.HIGH_REP,
  "Reverse Grip Bench Press": PROGRESSION.DEFAULT,
  "Reverse Grip Bent Over Row": PROGRESSION.DEFAULT,
  "Reverse Grip Lat Pulldown": PROGRESSION.DEFAULT,
  "Reverse Grip Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Reverse Grip Tricep Pushdown": PROGRESSION.HIGH_REP,
  "Reverse Nordic Curl": PROGRESSION.BODYWEIGHT_ONLY,
  "Reverse Plank": PROGRESSION.TIME_BASED,
  "Reverse Wrist Curl": PROGRESSION.HIGH_REP,
  "Roman Chair Side Bend": PROGRESSION.BODYWEIGHT_ONLY,
  "Romanian Deadlift": PROGRESSION.DEFAULT,

  // --- S ---
  "Scissor Kick": PROGRESSION.BODYWEIGHT_ONLY,
  "Seated Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Seated Cable Row": PROGRESSION.DEFAULT,
  "Seated Leg Curl": PROGRESSION.HEAVY_MACHINE,
  "Seated Overhead Press": PROGRESSION.DEFAULT,
  "Seated Row": PROGRESSION.DEFAULT,
  "Shoulder Press": PROGRESSION.DEFAULT,
  "Side Lateral Raise": PROGRESSION.HIGH_REP,
  "Side Plank": PROGRESSION.TIME_BASED,
  "Single Arm Cable Row": PROGRESSION.DEFAULT,
  "Single Arm Dumbbell Press": PROGRESSION.DEFAULT,
  "Single Arm Row": PROGRESSION.DEFAULT,
  "Single Leg Deadlift": PROGRESSION.DEFAULT,
  "Single Leg Glute Bridge": PROGRESSION.BODYWEIGHT_ONLY,
  "Single Leg Press": PROGRESSION.HEAVY_MACHINE,
  "Sit Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Skater Squat": PROGRESSION.HIGH_REP,
  "Skullcrusher": PROGRESSION.HIGH_REP,
  "Sled Push": PROGRESSION.BODYWEIGHT_ONLY,
  "Side Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Side Leg Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Side Lunge": PROGRESSION.HIGH_REP,
  "Side Lying Hip Adduction": PROGRESSION.BODYWEIGHT_ONLY,
  "Single Arm Hammer Curl": PROGRESSION.HIGH_REP,
  "Single Arm Tricep Pushdown": PROGRESSION.HIGH_REP,
  "Single Leg Dumbbell Deadlift": PROGRESSION.DEFAULT,
  "Single Leg Extension": PROGRESSION.HEAVY_MACHINE,
  "Single Leg Lying Leg Curl": PROGRESSION.HEAVY_MACHINE,
  "Single Leg Romanian Deadlift": PROGRESSION.DEFAULT,
  "Single Leg Seated Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Single Leg Squat": PROGRESSION.BODYWEIGHT_ONLY,
  "Sissy Squat": PROGRESSION.BODYWEIGHT_ONLY,
  "Smith Machine Bench Press": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Bent Over Row": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Bulgarian Split Squat": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Incline Bench Press": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Reverse Grip Bent Over Row": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Shoulder Press": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Shrug": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Sissy Squat": PROGRESSION.HEAVY_MACHINE,
  "Smith Machine Squat": PROGRESSION.HEAVY_MACHINE,
  "Snatch Pull": PROGRESSION.DEFAULT,
  "Snatch": PROGRESSION.DEFAULT,
  "Snatch Grip Deadlift": PROGRESSION.DEFAULT,
  "Snow Angel": PROGRESSION.BODYWEIGHT_ONLY,
  "Split Squat": PROGRESSION.HIGH_REP,
  "Split Squat Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Spider Curl": PROGRESSION.HIGH_REP,
  "Split Jerk": PROGRESSION.DEFAULT,
  "Spoto Press": PROGRESSION.DEFAULT,
  "Standing Cable Crunch": PROGRESSION.BODYWEIGHT_ONLY,
  "Standing Machine Lateral Raise": PROGRESSION.HIGH_REP,
  "Squat": PROGRESSION.DEFAULT,
  "Squat Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Stair Climber": PROGRESSION.BODYWEIGHT_ONLY,
  "Standing Calf Raise": PROGRESSION.HEAVY_MACHINE,
  "Standing Cable Row": PROGRESSION.DEFAULT,
  "Standing Leg Curl": PROGRESSION.HEAVY_MACHINE,
  "Standing Leg Raise": PROGRESSION.BODYWEIGHT_ONLY,
  "Step Up": PROGRESSION.HIGH_REP,
  "Step Up with Knee Raise": PROGRESSION.HIGH_REP,
  "Stiff Leg Deadlift": PROGRESSION.DEFAULT,
  "Straight Arm Pulldown": PROGRESSION.DEFAULT,
  "Strict Curl": PROGRESSION.HIGH_REP,
  "Strict Press": PROGRESSION.DEFAULT,
  "Sumo Deadlift": PROGRESSION.DEFAULT,
  "Sumo Squat": PROGRESSION.DEFAULT,
  "Superman": PROGRESSION.BODYWEIGHT_ONLY,
  "Safety Bar Squat": PROGRESSION.HEAVY_MACHINE,
  "Seated Dip Machine": PROGRESSION.HEAVY_MACHINE,
  "Seated Dumbbell Curl": PROGRESSION.HIGH_REP,
  "Seated Dumbbell Shoulder Press": PROGRESSION.DEFAULT,
  "Seated Dumbbell Tricep Extension": PROGRESSION.HIGH_REP,
  "Seated Hammer Curl": PROGRESSION.HIGH_REP,
  "Seated Shoulder Press": PROGRESSION.DEFAULT,
  "Seated Smith Machine Shoulder Press": PROGRESSION.HEAVY_MACHINE,
  "Shoulder Pin Press": PROGRESSION.DEFAULT,

  // --- T ---
  "Table Inverted Row": PROGRESSION.BODYWEIGHT_ONLY,
  "Tate Press": PROGRESSION.HIGH_REP,
  "Tiger Bend Push Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Toes to Bar": PROGRESSION.BODYWEIGHT_ONLY,
  "Torso Rotation Machine": PROGRESSION.HEAVY_MACHINE,
  "T Bar Row": PROGRESSION.DEFAULT,
  "Towel Pull Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Tricep Dips": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Tricep Extension": PROGRESSION.HIGH_REP,
  "Tricep Kickback": PROGRESSION.HIGH_REP,
  "Tricep Pushdown": PROGRESSION.HIGH_REP,
  "Tricep Rope Pushdown": PROGRESSION.HIGH_REP,
  "Trap Bar Deadlift": PROGRESSION.DEFAULT,
  "Tree Pose": PROGRESSION.BODYWEIGHT_ONLY,
  "Turkish Get Up": PROGRESSION.BODYWEIGHT_ONLY,

  // --- U ---
  "Upright Row": PROGRESSION.HIGH_REP,
  "Upright Shoulder Raise": PROGRESSION.HIGH_REP,
  "Uttanasana (Forward Bend)": PROGRESSION.BODYWEIGHT_ONLY,

  // --- V ---
  "V Squat": PROGRESSION.HEAVY_MACHINE,
  "V Ups": PROGRESSION.BODYWEIGHT_ONLY,
  "Vertical Leg Press": PROGRESSION.HEAVY_MACHINE,
  "Vertical Traction Machine": PROGRESSION.HEAVY_MACHINE,
  "Viking Press": PROGRESSION.DEFAULT,
  "V Sit": PROGRESSION.BODYWEIGHT_ONLY,
  "Vertical Jump": PROGRESSION.BODYWEIGHT_ONLY,
  "Volleyball Serve": PROGRESSION.BODYWEIGHT_ONLY,

  // --- W ---
  "Wall Ball Shot": PROGRESSION.BODYWEIGHT_ONLY,
  "Wall Sit": PROGRESSION.BODYWEIGHT_ONLY,
  "Walking Lunge": PROGRESSION.HIGH_REP,
  "Water Rowing": PROGRESSION.BODYWEIGHT_ONLY,
  "Weighted Pull Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Wide Grip Lat Pulldown": PROGRESSION.DEFAULT,
  "Waiter Curl": PROGRESSION.HIGH_REP,
  "Wall Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Wide Grip Bench Press": PROGRESSION.DEFAULT,
  "Wide Grip Chest Press": PROGRESSION.HEAVY_MACHINE,
  "Wide Grip Push Up": PROGRESSION.BODYWEIGHT_ONLY,
  "Wide Grip Seated Cable Row": PROGRESSION.DEFAULT,
  "Wide Grip Pull Up": PROGRESSION.BODYWEIGHT_LOADABLE,
  "Windmill": PROGRESSION.BODYWEIGHT_ONLY,
  "Wrist Curl": PROGRESSION.HIGH_REP,

  // --- X ---
  "X Band Walk": PROGRESSION.BODYWEIGHT_ONLY,

  // --- Y ---
  "Y Raise": PROGRESSION.HIGH_REP,
  "Yoke Walk": PROGRESSION.TIME_BASED,
  "Yates Row": PROGRESSION.DEFAULT,

  // --- Z ---
  "Z Press": PROGRESSION.DEFAULT,
  "Zercher Deadlift": PROGRESSION.DEFAULT,
  "Zottman Curl": PROGRESSION.HIGH_REP,
  "Zercher Squat": PROGRESSION.DEFAULT,
};
