export const ROTATION_GROUPS = {
  HIP_HINGE_BARBELL: [
    "Deadlift",
    "Romanian Deadlift",
    "Trap Bar Deadlift",
    "Pause Deadlift",
    "Rack Pull",
    "Behind the Back Deadlift",
    "Hex Bar Deadlift",
  ],

  SQUAT_PATTERN: [
    "Squat",
    "Leg Press",
    "Horizontal Leg Press",
    "Single Leg Press",
    "Vertical Leg Press",
    "Front Squat",
    "Goblet Squat",
    "Hack Squat",
    "Barbell Hack Squat",
    "Box Squat",
    "Bulgarian Split Squat",
    "Dumbbell Bulgarian Split Squat",
    "Dumbbell Split Squat",
    "Kettlebell Goblet Squat",
    "Pause Squat",
    "Smith Machine Bulgarian Split Squat",
    "Smith Machine Squat",
    "Split Squat",
  ],

  HORIZONTAL_PRESS: [
    "Bench Press",
    "Dumbbell Bench Press",
    "Machine Chest Press",
    "Smith Machine Bench Press",
    "Dumbbell Flyes",
    "Cable Chest Press",
    "Cable Crossover",
    "Dips",
    "Chest Dip",
    "Chest Press",
  ],

  INCLINE_PRESS: [
    "Incline Bench Press",
    "Incline Dumbbell Bench Press",
    "Incline Dumbbell Fly",
    "Smith Machine Incline Bench Press",
  ],

  VERTICAL_PRESS: [
    "Barbell Overhead Press",
    "Seated Dumbbell Shoulder Press",
    "Machine Shoulder Press",
    "Dumbbell Shoulder Press",
    "Machine Shoulder Press",
    "Smith Machine Shoulder Press",
    "Seated Smith Machine Shoulder Press",
    "Dumbbell Overhead Press",
    "One Arm Dumbbell Overhead Press",
    "Overhead Dumbbell Press",
    "Seated Overhead Press",
  ],

  TRAP_FOCUSED: [
    "Barbell Shrug",
    "Behind the Back Barbell Shrug",
    "Hex Bar Shrug",
  ],

  HORIZONTAL_PULL: [
    "Barbell Row",
    "Seated Cable Row",
    "Bent Over Dumbbell Row",
    "Bent Over Row",
    "Chest Supported Dumbbell Row",
    "Dumbbell Row",
    "One Arm Seated Cable Row",
    "One Arm Dumbbell Row",
    "One Arm Kettlebell Row",
    "Pendlay Row",
    "Smith Machine Bent Over Row",
    "T Bar Row",
    "Machine Row",
    "Cable Face Pull",
  ],

  VERTICAL_PULL: [
    "Pull-Ups",
    "Lat Pulldown",
    "Neutral Grip Pull Up",
    "Chin Ups",
    "One Arm Lat Pulldown",
    "Reverse Grip Lat Pulldown",
    "Straight Arm Pulldown",
  ],

  ARM_BICEPS: [
    "Barbell Curl",
    "EZ Bar Curl",
    "Reverse Grip Lat Pulldown",
    "Bayesian Curl",
    "Bicep Curl",
    "Cable Bicep Curl",
    "Chin Ups",
    "Dumbbell Bicep Curl",
    "Dumbbell Hammer Curl",
    "EZ Bar Preacher Curl",
    "Hammer Curl",
    "Incline Dumbbell Curl",
    "Incline Hammer Curl",
    "One Arm Cable Curl",
    "One Arm Dumbbell Preacher Curl",
    "Overhead Cable Curl",
    "Preacher Curl",
    "Seated Dumbbell Curl",
    "Seated Hammer Curl",
    "Barbell Concentration Curl",
    "Barbell Reverse Curl",
    "Dumbbell Reverse Curl",
  ],

  ARM_TRICEPS: [
    "Tricep Pushdown",
    "Overhead Tricep Extension",
    "Skullcrusher",
    "Tricep Dips",
    "Cable Overhead Tricep Extension",
    "Cable Rope Overhead Extension",
    "Arnold Press",
    "Bench Dips",
    "Cross Body Cable Tricep Extension",
    "Dumbbell Skullcrusher",
    "Dumbbell Tricep Extension",
    "EZ Bar Skullcrusher",
    "Lying Tricep Extension",
    "One Arm Cable Extension",
    "One Arm Dumbbell Triceps Extension",
    "Single Arm Tricep Pushdown",
    "Tate Press",
    "Triceps Extension",
    "Rope Push Down",
  ],

  CALVES: [
    "Barbell Calf Raise",
    "Dumbbell Calf Raise",
    "Hack Squat Calf Raise",
    "Leg Press Calf Raise",
    "Seated Calf Raise",
    "Smith Machine Calf Raise",
  ],
};
