import { Platform, StyleSheet } from "react-native";
import Colors from "../shared/Colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F7',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 40 : 30,
    marginBottom: 80,
  },
  feedbackContainer: {
    height: 100,
    backgroundColor: 'white',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 30 : 20,
    marginBottom: 20,
  },
  feedbackPressable: {
    backgroundColor: Colors.PRIMARY,
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  floatingFeedback: {
    position: 'absolute',
    bottom: 200,
    left: 20,
    right: 20,
    height: 150,
    backgroundColor: Colors.GRAY,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
    zIndex: 9999,
  },
  floatingBall: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.PRIMARY,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  floatingBallText: {
    fontSize: 24,
    color: Colors.WHITE,
  },
  notificationBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'red',
  },
  feedbackHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
    color: Colors.CHARCOAL,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#111',
    marginTop: 5,
  },
  weekHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    marginTop: 5,
    color: Colors.CHARCOAL,
    alignSelf: 'center',
  },
  subheader: {
    fontSize: 16,
    color: '#555',
    marginBottom: 10,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  subtitle: {
    fontSize: 14,
    marginBottom: 16,
    color: '#667085',
  },
  cardsContainer: { 
    gap: 12,
  },
  card: {
    backgroundColor: '#DDDDDD',
    borderRadius: 16,
    padding: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    borderColor: Colors.GRAY,
    borderWidth: 2,
  },
  workoutCard: {
    borderWidth: 2,
    backgroundColor: '#F2F2F2',
    borderRadius: 16,
    padding: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    borderColor: Colors.LIGHTGRAY,
    minHeight: 80,
    justifyContent: 'space-between',
  },
  day: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.CHARCOAL,
  },
  workout: {
    fontSize: 16,
    color: Colors.GRAY,
    fontWeight: '600',
  },
  rest: {
    fontSize: 16,
    color: '#888',
    fontWeight: '500',
  },
  restMessage: {
    fontSize: 16,
    fontStyle: 'italic',
    marginBottom: 20,
    color: '#666',
  },
  exerciseContainer: { 
    marginBottom: 12 
  },
  exerciseName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  exerciseDetails: {
    fontSize: 16,
    color: '#666',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EEEEEE',
  },
  loadingText: { 
    fontSize: 18, 
    color: '#555' 
  },
  back: { 
    marginBottom: 10 
  },
  selectedWorkoutContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 30,
  },
  backText: { 
    fontSize: 24, 
    color: Colors.PRIMARY, 
    fontWeight: 'bold' 
  },
  buttonContainer: { 
    marginTop: 20 
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    borderRadius: 16,
    padding: 20,
    maxHeight: '80%',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    overflow: 'hidden',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#fff',
  },
  modalOption: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  modalOptionText: {
    fontSize: 26,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#fff',
  },
  modalStartButton: {
    backgroundColor: Colors.PRIMARY,
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  modalStartText: {
    color: Colors.WHITE,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalCancel: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: Colors.CHARCOAL,
    marginTop: 10,
  },
  modalCancelText: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
    color: Colors.WHITE,
  },
  cardGridContainer: {
    backgroundColor: Colors.WHITE,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
    paddingBottom: 0,
    paddingTop: 16,
  },
  dayLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  todayBadge: {
    position: 'absolute',
    top: -35,
    left: '50%',
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    transform: [{ translateX: -40 }],
    backgroundColor: Colors.PRIMARY,
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 20,
    zIndex: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  todayBadgeText: {
    color: Colors.WHITE,
    fontSize: 14,
    fontWeight: 'bold',
    alignSelf: 'center'
  },
  separator: {
    height: 1,
    width: '120%',
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 1,
    borderRadius: 10,
    marginBottom: 10,
  },
  adjustmentContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 30,
    marginHorizontal: 0,
    borderColor: '#E1E3E8',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
    alignSelf: 'center',
    width: '100%',
  },
  adjustmentTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.CHARCOAL || '#333',
    shadowColor: 'black',
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 2
  },
  adjustmentText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#444',
    fontWeight: '500'
  },
  collapsedText: { 
    overflow: 'hidden', 
    height: 0 
  },
  toggleText: {
    color: Colors.WHITE,
    fontWeight: 'bold',
    marginTop: 5,
    backgroundColor: Colors.PRIMARY,
    width: 90,
    height: 24,
    textAlign: 'center',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
  },
  breakBanner: {
    backgroundColor: "#fff3cd",
    borderLeftWidth: 4,
    borderLeftColor: "#ffc107",
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    marginTop: 10,
  },
  breakText: {
    color: "#856404",
    fontWeight: "600",
    marginBottom: 8,
    fontSize: 14,
  },
  breakButton: {
    backgroundColor: "#ffc107",
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: "center",
  },
  breakButtonText: { 
    color: "#fff", 
    fontWeight: 'bold' 
  },
  cardGridWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 30,
    overflow: 'visible',
  },
  cardItem: { 
    width: '48%', 
    marginBottom: 16,
    overflow: 'visible',
  },
  dayIconWrapper: {
    position: "absolute",
    alignItems: 'center',
    justifyContent: 'center',
    top: -12,
    left: -12,
    zIndex: 2,
    backgroundColor: Colors.LIGHTGRAY,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    borderRadius: 100,
    width: 35,
    height: 35,
  },
  heroContainer: {
    borderRadius: 24,
    padding: 18,
    marginTop: 6,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 6,
  },
  heroTop: {
    marginBottom: 12,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: Colors.WHITE,
  },
  heroQuote: {
    marginTop: 6,
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    fontStyle: 'italic',
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  heroChip: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  heroChipText: {
    color: Colors.WHITE,
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 0.5,
  },
  heroStatus: {
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '600',
    fontSize: 14,
  },
  heroCtaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  primaryCta: {
    backgroundColor: Colors.WHITE,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
    elevation: 3,
  },
  primaryCtaDisabled: {
    opacity: 0.5,
  },
  primaryCtaText: {
    color: '#1C1C1E',
    fontWeight: '700',
    fontSize: 16,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderColor: '#E1E3E8',
    borderWidth: 1,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.CHARCOAL,
  },
  statLabel: {
    marginTop: 4,
    fontSize: 12,
    color: '#667085',
    fontWeight: '600',
    textAlign: 'center',
  },
  weekStrip: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
    borderColor: '#E1E3E8',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
    height: 170,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.CHARCOAL,
    marginBottom: 10,
  },
  weekStripInner: {
    flexDirection: 'row',
    gap: 10,
    paddingRight: 10,
    paddingLeft: 10,
    paddingTop: 5,
  },
  weekPillItem: {
    marginRight: 4,
  },
  dayPill: {
    width: 92,
    borderRadius: 16,
    backgroundColor: '#F6F7FB',
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderColor: '#E6E8EF',
    borderWidth: 1,
  },
  dayPillRest: {
    width: 92,
    borderRadius: 16,
    backgroundColor: '#dee0e4',
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderColor: '#E6E8EF',
    borderWidth: 1,
  },
  dayPillActive: {
    borderColor: Colors.PRIMARY,
    shadowColor: Colors.PRIMARY,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  dayPillDone: {
    backgroundColor: '#E9F8EF',
    borderColor: '#A6E3B5',
  },
  dayPillIcon: {
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 2,
  },
  dayPillIconDone: {
    backgroundColor: Colors.GREEN,
  },
  dayPillLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.CHARCOAL,
  },
  dayPillSub: {
    marginTop: 2,
    fontSize: 11,
    color: '#667085',
    fontWeight: '600',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    },
  feedbackCard: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 5,
    },
  feedbackHeader: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    color: Colors.CHARCOAL,
    },
  feedbackOption: {
    backgroundColor: '#f1f1f1',
    borderRadius: 8,
    padding: 12,
    marginVertical: 6,
    alignItems: 'center',
},
  feedbackSub: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
    color: Colors.GRAY,
    },
  feedbackInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    padding: 10,
    marginVertical: 10,
    color: Colors.CHARCOAL,
    },
  submitButton: {
    backgroundColor: Colors.PRIMARY,
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
    },
  submitButtonText: {
    color: Colors.WHITE,
    fontWeight: 'bold',
    textAlign: 'center',
    },
    optionText: {
    fontWeight: 'bold',
    color: Colors.CHARCOAL,
    },
});
